### ISSUE TITLE
Support specifying columns on INSERT

### ISSUE THREAD

**Issue by nadzimo** [kayak/pypika#104]
I'm trying to build such a query:  
`INSERT INTO some_table (column1, column2) VALUES(val1, val2)`
Is it doable now?

**Comment by mikeengland** [comment]
Hi @nadzimo. It is! Please see the relevant documentation at http://pypika.readthedocs.io/en/latest/2_tutorial.html#insert-with-a-select-query.

**Comment by nadzimo** [comment]
thank you
