### ISSUE TITLE
as_() omitting 'as'

### ISSUE THREAD

**Issue by nadzimo** [kayak/pypika#106]
I tried the example in the tutorial but the as_() seems to be omitting the 'as' word. 
```
from pypika import Query, Table
accounts = Table('accounts')
q = Query.from_(accounts).select(
     (accounts.revenue - accounts.cost).as_('profit')
)
q.get_sql()
# 'SELECT revenue-cost profit FROM accounts'
```

**Comment by mikeengland** [comment]
Hi @nadzimo, 

In the output `SELECT revenue-cost profit FROM accounts`, the profit word is the alias. The 'as' does  not actually need to be present.

Let us know if you have any further trouble with this. Closing it for now.
