### ISSUE TITLE
Union queries with `+` seems to be broken when used for more than 2 queries

### ISSUE THREAD

**Issue by inkmix** [kayak/pypika#111]
**Example**
```
from pypika import Tables, Query
a,b,c = Tables('a', 'b', 'c')
qa=Query.from_(a).select(a.a, 'name')
qb=Query.from_(b).select(b.b, 'name')
qc=Query.from_(c).select(c.c, 'name')

qa+qb
str(qa+qb)  # 1)
qa+qb+qc
str(qa+qb+qc)  # 2)
```

this used to output
1) `'(SELECT "a","name" FROM "a") UNION (SELECT "b","name" FROM "b")'`
2) `'((SELECT "a","name" FROM "a") UNION (SELECT "b","name" FROM "b")) UNION (SELECT "c","name" FROM "c")'`

**Issue**
Now, it out puts for 
1) still the same but for 
2) `'(SELECT "a","name" FROM "a") UNION (SELECT "b","name" FROM "b")+SELECT "c","name" FROM "c"'`

`qa+qb` is a `UnionQuery`, but `qa+qb+qc` is an `ArithmeticExpression`

if my bisect was correct, this was introduced in commit `3e850da1fdca72e0766a4e7b5bceceb88a97acaa`

**work around**
using `.union()` instead of the `+` sign still works fine

**Comment by twheys** [comment]
Ah i think the `UnionQuery` class needs to define `__add__` and __mul__`
