### ISSUE TITLE
SELECTs with explicit fields fail on sqlite with a "row value misused"

### ISSUE THREAD

**Issue by hawkowl** [kayak/pypika#123]
Pypika generates SQL like ``SELECT ("Col", "Name") FROM "Table"``, which trips up SQLite. SQLite seems to be happy with ``SELECT Col, Name FROM "Table"``, though.

This appears to be the problem, as the brackets are always added in: https://github.com/kayak/pypika/blob/master/pypika/queries.py#L744

**Comment by twheys** [comment]
Can you please share the python code you are using to generate this?

**Comment by hawkowl** [comment]
lol in trying to make a short reproduction I realised the error was on my side. Sorry!

```>>> Query.from_("Example").select("foo", "bar", "baz")
SELECT "foo","bar","baz" FROM "Example"
>>> Query.from_("Example").select(["foo", "bar", "baz"])
SELECT ('foo','bar','baz') FROM "Example"
```
I was dynamically generating the select() arguments and didn't unpack the list.

Is accepting a list something the API shouldn't let you do, or is there another use for it?

**Comment by twheys** [comment]
Yeah, that's intentionally because some database vendors support tuples, so pypika supports them as well.
