### ISSUE TITLE
Regex mathing in Redshift

### ISSUE THREAD

**Issue by GilZ** [kayak/pypika#125]
One of the functions that Redshift has and Postgres hasn't is `REGEXP_MATCHES` (see https://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-functions.html).

But when calling `fn.RegexpLike`, we get `SELECT REGEXP_MATCHES`, which doesn't work.

Can you please replace it with something like `REGEXP_SUBSTR`?

**Comment by mikeengland** [comment]
Hi @GilZ 
Some platforms support REGEXP_LIKE, so we have added that to the functions file. We can always add a REGEXP_SUBSTR function, but in the meantime, you can just inherit from the Function class and create your own RegexpSubstr function e.g.

```python
class RegexpSubStr(Function):
    def __init__(self, field, alias=None):
        super(RegexpSubStr, self).__init__('REGEXP_SUBSTR', field, alias=alias)
```
