### ISSUE TITLE
Field aliasing i.e. "harcodedvalue AS customcolumn" not working properly

### ISSUE THREAD

**Issue by Pithikos** [kayak/pypika#141]
Having the code below

```python
Query.from_('mytable').select(Field('HTTP').as_('protocol'))
```

Produces

    SELECT "HTTP" "protocol" FROM "mytable"

But what is expected is

    SELECT 'HTTP' "protocol" FROM "mytable"

Or

    SELECT 'HTTP' AS "protocol" FROM "mytable"

**Comment by Pithikos** [comment]
Closed since the issue seems to be that I use `str(query)` instead of `query.get_sql()`. Still this is a bit weird behaviour to me.

**Comment by twheys** [comment]
A Field is meant to be a column in the table. If you want to select a raw string value, you should use the ValueWrapper class

`Query.from_('mytable').select(ValueWrapper('HTTP').as_('protocol'))`
