### ISSUE TITLE
Implementation of Postgres's INSERT features

### ISSUE THREAD

**Issue by butla** [kayak/pypika#149]
Is there some way of doing `INSERT INTO ... ON CONFLICT ... RETURNING ...` in Pypika other than just appending a string at the back of Pypika's output?

Maybe there's a built in way of appending raw SQL to the query? I couldn't find anything in the docs about that.

["Upserts" and returning from inserts](https://www.postgresql.org/docs/9.6/static/sql-insert.html) are great features in Postgres.

**Comment by twheys** [comment]
Not currently supporting those keywords but it would be relatively straight forward to add. There isn't a way to append raw SQL to the query, but you can manipulate the string that pypika serializes.

**Comment by butla** [comment]
@twheys is there some documentation or maybe some valuable docstrings in the code that could guide in adding these features?

**Comment by twheys** [comment]
If you're interested in adding it yourself, I would recommend looking at the code, Particularly `pypika.dialects.PostgreQueryBuilder`

**Comment by Mehran-sh** [comment]
I implemented this and there is a pull request on #202
