### ISSUE TITLE
group_concat

### ISSUE THREAD

**Issue by quanlinhe** [kayak/pypika#151]
How to define a  group_concat function ?

**Comment by twheys** [comment]
Take a look at how the `Function` class is extended https://github.com/kayak/pypika/blob/master/pypika/functions.py#L132

**Comment by cbows** [comment]
For anybody stumbling over this, I have implemented it like this (for MySQL)

```python
from pypika.functions import DistinctOptionFunction
from pypika import Field, MySQLQuery, Order

QUOTE_CHAR = MySQLQuery._builder().QUOTE_CHAR

class GroupConcat(DistinctOptionFunction):
    def __init__(self, term: Field, order=Order.asc, sep=",", alias=None):
        super().__init__("GROUP_CONCAT", term, alias=alias)
        self.term_ = term.get_sql(with_alias=False, quote_char=QUOTE_CHAR)
        self.order = order
        self.sep = self.wrap_constant(sep)

    def get_special_params_sql(self, **kwargs):
        return f"ORDER BY {self.term_} {self.order.value} SEPARATOR {self.sep}"
```

Maybe there is an easier way, but this has worked for me.

If you just want to use the function with its defaults, you could get away with a simpler implementation

```python
class GroupConcat(DistinctOptionFunction):
    def __init__(self, term: Field, alias=None):
        super().__init__("GROUP_CONCAT", term, alias=alias)
```

Using `DistinctOptionFunction` allows you to do `GroupConcat(my_field).distinct()` which will prepend a `DISTINCT` before the first argument.
