### ISSUE TITLE
Object corrupted | Current timestamp added to Query object in case statements

### ISSUE THREAD

**Issue by saivarunr** [kayak/pypika#157]
Check the bolder content in the below output:

> 

SELECT `t`.`week_dates`,AVG(CASE WHEN `t`.`week_dates`='2014-04-01' THEN `t`.`sales_qty` ELSE NULL END) `2014-04-01`,AVG(CASE WHEN `t`.`week_dates`='2014-04-08' THEN `t`.`sales_qty` ELSE NULL END) `2014-04-08`,AVG(CASE WHEN `t`.`week_dates`='2014-04-15' THEN `t`.`sales_qty` ELSE NULL END) `2014-04-15`,AVG(CASE WHEN `t`.`week_dates`='2014-04-22' THEN `t`.`sales_qty` ELSE NULL END) `2014-04-22`,AVG(CASE WHEN `t`.`week_dates`='2014-04-29' THEN `t`.`sales_qty` ELSE NULL END) `2014-04-29`,AVG(CASE WHEN `t`.`week_dates`='2014-05-06' THEN `t`.`sales_qty` ELSE NULL END) `2014-05-06`,AVG(CASE WHEN `t`.`week_dates`='2014-05-13' THEN `t`.`sales_qty` ELSE NULL END) `2014-05-13`,AVG(CASE WHEN `t`.`week_dates`='2014-05-20' THEN `t`.`sales_qty` ELSE NULL END) `2014-05-20`,AVG(CASE WHEN `t`.`week_dates`='2014-05-27' THEN `t`.`sales_qty` ELSE NULL END) `2014-05-27`,AVG(CASE WHEN `t`.`week_dates`='2014-06-03' THEN `t`.`sales_qty` ELSE NULL END) `2014-06-03`,AVG(CASE WHEN `t`.`week_dates`='2014-06-10' THEN `t`.`sales_qty` ELSE NULL END) `2014-06-10`,AVG(CASE WHEN `t`.`week_dates`='2014-06-17' THEN `t`.`sales_qty` ELSE NULL END) `2014-06-17`,AVG(CASE WHEN `t`.`week_dates`='2014-06-24' THEN `t`.`sales_qty` ELSE NULL END) `2014-06-24`,AVG(CASE WHEN `t`.`week_dates`='2014-07-01' THEN `t`.`sales_qty` ELSE NULL END) `2014-07-01`,AVG(CASE WHEN `t`.`week_dates`='2014-07-08' THEN `t`.`sales_qty` ELSE NULL END) `2014-07-08`,AVG(CASE WHEN `t`.`week_dates`='2014-07-15' THEN `t`.`sales_qty` ELSE NULL END) `2014-07-15`,AVG(CASE WHEN `t`.`week_dates`='2014-07-22' THEN `t`.`sales_qty` ELSE NULL END) `2014-07-22`,AVG(CASE WHEN `t`.`week_dates`='2014-07-29' THEN `t`.`sales_qty` ELSE NULL END) `2014-07-29`,AVG(CASE WHEN `t`.`week_dates`='2014-08-05' THEN `t`.`sales_qty` ELSE NULL END) `2014-08-05`,AVG(CASE WHEN `t`.`week_dates`='2014-08-12' THEN `t`.`sales_qty` ELSE NULL END) `2014-08-12`,AVG(CASE WHEN `t`.`week_dates`='2014-08-19' THEN `t`.`sales_qty` ELSE NULL END) `2014-08-19`,AVG(CASE WHEN `t`.`week_dates`='2014-08-26' THEN `t`.`sales_qty` ELSE NULL END) `2014-08-26`,AVG(CASE WHEN `t`.`week_dates`='2014-09-02' THEN `t`.`sales_qty` ELSE NULL END) `2014-09-02`,AVG(CASE WHEN `t`.`week_dates`='2014-09-09' THEN `t`.`sales_qty` ELSE NULL END) `2014-09-09`,AVG(CASE WHEN `t`.`week_dates`='2014-09-16' THEN `t`.`sales_qty` ELSE NULL END) `2014-09-16`,AVG(CASE WHEN `t`.`week_dates`='2014-09-23' THEN `t`.`sales_qty` ELSE NULL END) `2014-09-23`,AVG(CASE WHEN `t`.`week_dates`='2014-09-30' THEN `t`.`sales_qty` ELSE NULL END) `2014-09-30`,AVG(CASE WHEN `t`.`week_dates`='2014-10-07' THEN `t`.`sales_qty` ELSE NULL END) `2014-10-07`,AVG(CASE WHEN `t`.`week_dates`='2014-10-14' THEN `t`.`sales_qty` ELSE NULL END) `2014-10-14`,AVG(CASE WHEN `t`.`week_dates`='2014-10-21' THEN `t`.`sales_qty` ELSE NULL END) `2014-10-21`,AVG(CASE WHEN `t`.`week_dates`='2014-10-28' THEN `t`.`sales_qty` ELSE NULL END) `2014-10-28`,AVG(CASE WHEN `t`.`week_dates`='2014-11-04' THEN `t`.`sales_qty` ELSE NULL END) `2014-11-04`,AVG(CASE WHEN `t`.`week_dates`='2014-11-11' THEN `t`.`sales_qty` ELSE NULL END) `2014-11-11`,AVG(CASE WHEN `t`.`week_dates`='2014-11-18' THEN `t`.`sales_qty` ELSE NULL END) `2014-11-18`,AVG(CASE WHEN `t`.`week_dates`='2014-11-25' THEN `t`.`sales_qty` ELSE NULL END) `2014-11-25`,AVG(CASE WHEN `t`.`week_dates`='2014-12-02' THEN `t`.`sales_qty` ELSE NULL END) `2014-12-02`,AVG(CASE WHEN `t`.`week_dates`='2014-12-09' THEN `t`.`sales_qty` ELSE NULL END) `2014-12-09`,AVG(CASE WHEN `t`.`week_dates`='2014-12-16' THEN `t`.`sales_qty` ELSE NULL END) `2014-12-16`,AVG(CASE WHEN `t`.`week_dates`='2014-12-23' THEN `t`.`sales_qty` ELSE NULL END) `2014-12-23`,AVG(CASE WHEN `t`.`week_dates`='2014-12-30' THEN `t`.`sales_qty` ELSE NULL END) `2014-12-30`,AVG(CASE WHEN `t`.`week_dates`='2015-01-06' THEN `t`.`sales_qty` ELSE NULL END) `2015-01-06`,AVG(CASE WHEN `t`.`week_dates`='2015-01-13' THEN `t`.`sales_qty` ELSE NULL END) `2015-01-13`,AVG(CASE WHEN `t`.`week_dates`='2015-01-20' THEN `t`.`sales_qty` ELSE NULL END) `2015-01-20`,AVG(CASE WHEN `t`.`week_dates`='2015-01-27' THEN `t`.`sales_qty` ELSE NULL END) `2015-01-27`,AVG(CASE WHEN `t`.`week_dates`='2015-02-03' THEN `t`.`sales_qty` ELSE NULL END) `2015-02-03`,AVG(CASE WHEN `t`.`week_dates`='2015-02-10' THEN `t`.`sales_qty` ELSE NULL END) `2015-02-10`,AVG(CASE WHEN `t`.`week_dates`='2015-02-17' THEN `t`.`sales_qty` ELSE NULL END) `2015-02-17`,AVG(CASE WHEN `t`.`week_dates`='2015-02-24' THEN `t`.`sales_qty` ELSE NULL END) `2015-02-24`,AVG(CASE WHEN `t`.`week_dates`='2015-03-03' THEN `t`.`sales_qty` ELSE NULL END) `2015-03-03`,AVG(CASE WHEN `t`.`week_dates`='2015-03-10' THEN `t`.`sales_qty` ELSE NULL END) `2015-03-10`,AVG(CASE WHEN `t`.`week_dates`='2015-03-17' THEN `t`.`sales_qty` ELSE NULL END) `2015-03-17`,AVG(CASE WHEN `t`.`week_dates`='2015-03-24' THEN `t`.`sales_qty` ELSE NULL END) `2015-03-24`,AVG(CASE WHEN `t`.`week_dates`='2015-03-31' THEN `t`.`sales_qty` ELSE NULL END) `2015-03-31`,AVG(CASE WHEN `t`.`week_dates`='2015-04-07' THEN `t`.`sales_qty` ELSE NULL END) `2015-04-07`,AVG(CASE WHEN `t`.`week_dates`='2015-04-14' THEN `t`.`sales_qty` ELSE NULL END) `2015-04-14`,AVG(CASE WHEN `t`.`week_dates`='2015-04-21' THEN `t`.`sales_qty` ELSE NULL END) `2015-04-21`,AVG(CASE WHEN `t`.`week_dates`='2015-04-28' THEN `t`.`sales_qty` ELSE NULL END) `2015-04-28`,AVG(CASE WHEN `t`.`week_dates`='2015-05-05' THEN `t`.`sales_qty` ELSE NULL END) `2015-05-05`,AVG(CASE WHEN `t`.`week_dates`='2015-05-12' THEN `t`.`sales_qty` ELSE NULL END) `2015-05-12`,AVG(CASE WHEN `t`.`week_dates`='2015-05-19' THEN `t`.`sales_qty` ELSE NULL END) `2015-05-19`,AVG(CASE WHEN `t`.`week_dates`='2015-05-26' THEN `t`.`sales_qty` ELSE NULL END) `2015-05-26`,AVG(CASE WHEN `t`.`week_dates`='2015-06-02' THEN `t`.`sales_qty` ELSE NULL END) `2015-06-02`,AVG(CASE WHEN `t`.`week_dates`='2015-06-09' THEN `t`.`sales_qty` ELSE NULL END) `2015-06-09`,AVG(CASE WHEN `t`.`week_dates`='2015-06-16' THEN `t`.`sales_qty` ELSE NULL END) `2015-06-16`,AVG(CASE WHEN `t`.`week_dates`='2015-06-23' THEN `t`.`sales_qty` ELSE NULL END) `2015-06-23`,AVG(CASE WHEN `t`.`week_dates`='2015-06-30' THEN `t`.`sales_qty` ELSE NULL END) `2015-06-30`,AVG(CASE WHEN `t`.`week_dates`='2015-07-07' THEN `t`.`sales_qty` ELSE NULL END) `2015-07-07`,AVG(CASE WHEN `t`.`week_dates`='2015-07-14' THEN `t`.`sales_qty` ELSE NULL END) `2015-07-14`,AVG(CASE WHEN `t`.`week_dates`='2015-07-21' THEN `t`.`sales_qty` ELSE NULL END) `2015-07-21`,AVG(CASE WHEN `t`.`week_dates`='2015-07-28' THEN `t`.`sales_qty` ELSE NULL END) `2015-07-28`,AVG(CASE WHEN `t`.`week_dates`='2015-08-04' THEN `t`.`sales_qty` ELSE NULL END) `2015-08-04`,AVG(CASE WHEN `t`.`week_dates`='2015-08-11' THEN `t`.`sales_qty` ELSE NULL END) `2015-08-11`,AVG(CASE WHEN `t`.`week_dates`='2015-08-18' THEN `t`.`sales_qty` ELSE NULL END) `2015-08-18`,AVG(CASE WHEN `t`.`week_dates`='2015-08-25' THEN `t`.`sales_qty` ELSE NULL END) `2015-08-25`,AVG(CASE WHEN `t`.`week_dates`='2015-09-01' THEN `t`.`sales_qty` ELSE NULL END) `2015-09-01`,AVG(CASE WHEN `t`.`week_dates`='2015-09-08' THEN `t`.`sales_qty` ELSE NULL END) `2015-09-08`,AVG(CASE WHEN `t`.`week_dates`='2015-09-15' THEN `t`.`sales_qty` ELSE NULL END) `2015-09-15`,AVG(CASE WHEN `t`.`week_dates`='2015-09-22' THEN `t`.`sales_qty` ELSE NULL END) `2015-09-22`,AVG(CASE WHEN `t`.`week_dates`='2015-09-29' THEN `t`.`sales_qty` ELSE NULL END) `2015-09-29`,AVG(CASE WHEN `t`.`week_dates`='2015-10-06' THEN `t`.`sales_qty` ELSE NULL END) `2015-10-06`,AVG(CASE WHEN `t`.`week_dates`='2015-10-13' THEN `t`.`sales_qty` ELSE NULL END) `2015-10-13`,AVG(CASE WHEN `t`.`week_dates`='2015-10-20' THEN `t`.`sales_qty` ELSE NULL END) `2015-10-20`,AVG(CASE WHEN `t`.`week_dates`='2015-10-27' THEN `t`.`sales_qty` ELSE NULL END) `2015-10-27`,AVG(CASE WHEN `t`.`week_dates`='2015-11-03' THEN `t`.`sales_qty` ELSE NULL END) `2015-11-03`,AVG(CASE WHEN `t`.`week_dates`='2015-11-10' THEN `t`.`sales_qty` ELSE NULL END) `2015-11-10`,AVG(CASE WHEN `t`.`week_dates`='2015-11-17' THEN `t`.`sales_qty` ELSE NULL END) `2015-11-17`,AVG(CASE WHEN `t`.`week_dates`='2015-11-24' THEN `t`.`sales_qty` ELSE NULL END) `2015-11-24`,AVG(CASE WHEN `t`.`week_dates`='2015-12-01' THEN `t`.`sales_qty` ELSE NULL END) `2015-12-01`,AVG(CASE WHEN `t`.`week_dates`='2015-12-08' THEN `t`.`sales_qty` ELSE NULL END) `2015-12-08`,AVG(CASE WHEN `t`.`week_dates`='2015-12-15' THEN `t`.`sales_qty` ELSE NULL END) `2015-12-15`,AVG(CASE WHEN `t`.`week_dates`='2015-12-22' THEN `t`.`sales_qty` ELSE NULL END) `2015-12-22`,AVG(CASE WHEN `t`.`week_dates`='2015-12-29' THEN `t`.`sales_qty` ELSE NULL END) `2015-12-29`,AVG(CASE WHEN `t`.`week_dates`='2016-01-05' THEN `t`.`sales_qty` ELSE NULL END) `2016-01-05`,AVG(CASE WHEN `t`.`week_dates`='2016-01-12' THEN `t`.`sales_qty` ELSE NULL END) `2016-01-12`,AVG(CASE WHEN `t`.`week_dates`='2016-01-19' THEN `t`.`sales_qty` ELSE NULL END) `2016-01-19`,AVG(CASE WHEN `t`.`week_dates`='2016-01-26' THEN `t`.`sales_qty` ELSE NULL END) `2016-01-26`,AVG(CASE WHEN `t`.`week_dates`='2016-02-02' THEN `t`.`sales_qty` ELSE NULL END) `2016-02-02`,AVG(CASE WHEN `t`.`week_dates`='2016-02-09' THEN `t`.`sales_qty` ELSE NULL END) `2016-02-09`,AVG(CASE WHEN `t`.`week_dates`='2016-02-16' THEN `t`.`sales_qty` ELSE NULL END) `2016-02-16`,AVG(CASE WHEN `t`.`week_dates`='2016-02-23' THEN `t`.`sales_qty` ELSE NULL END) `2016-02-23`,AVG(CASE WHEN `t`.`week_dates`='2016-03-01' THEN `t`.`sales_qty` ELSE NULL END) `2016-03-01`,AVG(CASE WHEN `t`.`week_dates`='2016-03-08' THEN `t`.`sales_qty` ELSE NULL END) `2016-03-08`,AVG(CASE WHEN `t`.`week_dates`='2016-03-15' THEN `t`.`sales_qty` ELSE NULL END) `2016-03-15`,AVG(CASE WHEN `t`.`week_dates`='2016-03-22' THEN `t`.`sales_qty` ELSE NULL END) `2016-03-22`,AVG(CASE WHEN `t`.`week_dates`='2016-03-29' THEN `t`.`sales_qty` ELSE NULL END) `2016-03-29`,AVG(CASE WHEN `t`.`week_dates`='2016-04-05' THEN `t`.`sales_qty` ELSE NULL END) `2016-04-05`,AVG(CASE WHEN `t`.`week_dates`='2016-04-12' THEN `t`.`sales_qty` ELSE NULL END) `2016-04-12`,AVG(CASE WHEN `t`.`week_dates`='2016-04-19' THEN `t`.`sales_qty` ELSE NULL END) `2016-04-19`,AVG(CASE WHEN `t`.`week_dates`='2016-04-26' THEN `t`.`sales_qty` ELSE NULL END) `2016-04-26`,AVG(CASE WHEN `t`.`week_dates`='2016-05-03' THEN `t`.`sales_qty` ELSE NULL END) `2016-05-03`,AVG(CASE WHEN `t`.`week_dates`='2016-05-10' THEN `t`.`sales_qty` ELSE NULL END) `2016-05-10`,AVG(CASE WHEN `t`.`week_dates`='2016-05-17' THEN `t`.`sales_qty` ELSE NULL END) `2016-05-17`,AVG(CASE WHEN `t`.`week_dates`='2016-05-24' THEN `t`.`sales_qty` ELSE NULL END) `2016-05-24`,AVG(CASE WHEN `t`.`week_dates`='2016-05-31' THEN `t`.`sales_qty` ELSE NULL END) `2016-05-31`,AVG(CASE WHEN `t`.`week_dates`='2016-06-07' THEN `t`.`sales_qty` ELSE NULL END) `2016-06-07`,AVG(CASE WHEN `t`.`week_dates`='2016-06-14' THEN `t`.`sales_qty` ELSE NULL END) `2016-06-14`,AVG(CASE WHEN `t`.`week_dates`='2016-06-21' THEN `t`.`sales_qty` ELSE NULL END) `2016-06-21`,AVG(CASE WHEN `t`.`week_dates`='2016-06-28' THEN `t`.`sales_qty` ELSE NULL END) `2016-06-28`,AVG(CASE WHEN `t`.`week_dates`='2016-07-05' THEN `t`.`sales_qty` ELSE NULL END) `2016-07-05`,AVG(CASE WHEN `t`.`week_dates`='2016-07-12' THEN `t`.`sales_qty` ELSE NULL END) `2016-07-12`,AVG(CASE WHEN `t`.`week_dates`='2016-07-19' THEN `t`.`sales_qty` ELSE NULL END) `2016-07-19`,AVG(CASE WHEN `t`.`week_dates`='2016-07-26' THEN `t`.`sales_qty` ELSE NULL END) `2016-07-26`,AVG(CASE WHEN `t`.`week_dates`='2016-08-02' THEN `t`.`sales_qty` ELSE NULL END) `2016-08-02`,AVG(CASE WHEN `t`.`week_dates`='2016-08-09' THEN `t`.`sales_qty` ELSE NULL END) `2016-08-09`,AVG(CASE WHEN `t`.`week_dates`='2016-08-16' THEN `t`.`sales_qty` ELSE NULL END) `2016-08-16`,AVG(CASE WHEN `t`.`week_dates`='2016-08-23' THEN `t`.`sales_qty` ELSE NULL END) `2016-08-23`,AVG(CASE WHEN `t`.`week_dates`='2016-08-30' THEN `t`.`sales_qty` ELSE NULL END) `2016-08-30`,AVG(CASE WHEN `t`.`week_dates`='2016-09-06' THEN `t`.`sales_qty` ELSE NULL END) `2016-09-06`,AVG(CASE WHEN `t`.`week_dates`='2016-09-13' THEN `t`.`sales_qty` ELSE NULL END) `2016-09-13`,AVG(CASE WHEN `t`.`week_dates`='2016-09-20' THEN `t`.`sales_qty` ELSE NULL END) `2016-09-20`,AVG(CASE WHEN `t`.`week_dates`='2016-09-27' THEN `t`.`sales_qty` ELSE NULL END) `2016-09-27`,AVG(CASE WHEN `t`.`week_dates`='2016-10-04' THEN `t`.`sales_qty` ELSE NULL END) `2016-10-04`,AVG(CASE WHEN `t`.`week_dates`='2016-10-11' THEN `t`.`sales_qty` ELSE NULL END) `2016-10-11`,AVG(CASE WHEN `t`.`week_dates`='2016-10-18' THEN `t`.`sales_qty` ELSE NULL END) `2016-10-18`,AVG(CASE WHEN `t`.`week_dates`='2016-10-25' THEN `t`.`sales_qty` ELSE NULL END) `2016-10-25`,AVG(CASE WHEN `t`.`week_dates`='2016-11-01' THEN `t`.`sales_qty` ELSE NULL END) `2016-11-01`,AVG(CASE WHEN `t`.`week_dates`='2016-11-08' THEN `t`.`sales_qty` ELSE NULL END) `2016-11-08`,AVG(CASE WHEN `t`.`week_dates`='2016-11-15' THEN `t`.`sales_qty` ELSE NULL END) `2016-11-15`,AVG(CASE WHEN `t`.`week_dates`='2016-11-22' THEN `t`.`sales_qty` ELSE NULL END) `2016-11-22`,AVG(CASE WHEN `t`.`week_dates`='2016-11-29' THEN `t`.`sales_qty` ELSE NULL END) `2016-11-29`,AVG(CASE WHEN `t`.`week_dates`='2016-12-06' THEN `t`.`sales_qty` ELSE NULL END) `2016-12-06`,AVG(CASE WHEN `t`.`week_dates`='2016-12-13' THEN `t`.`sales_qty` ELSE NULL END) `2016-12-13`,AVG(CASE WHEN `t`.`week_dates`='2016-12-20' THEN `t`.`sales_qty` ELSE NULL END) `2016-12-20`,AVG(CASE WHEN `t`.`week_dates`='2016-12-27' THEN `t`.`sales_qty` ELSE NULL END) `2016-12-27`,AVG(CASE WHEN `t`.`week_dates`='2017-01-03' THEN `t`.`sales_qty` ELSE NULL END) `2017-01-03`,AVG(CASE WHEN `t`.`week_dates`='2017-01-10' THEN `t`.`sales_qty` ELSE NULL END) `2017-01-10`,AVG(CASE WHEN `t`.`week_dates`='2017-01-17' THEN `t`.`sales_qty` ELSE NULL END) `2017-01-17`,AVG(CASE WHEN `t`.`week_dates`='2017-01-24' THEN `t`.`sales_qty` ELSE NULL END) `2017-01-24`,AVG(CASE WHEN `t`.`week_dates`='2017-01-31' THEN `t`.`sales_qty` ELSE NULL END) `2017-01-31`,AVG(CASE WHEN `t`.`week_dates`='2017-02-07' THEN `t`.`sales_qty` ELSE NULL END) `2017-02-07`,AVG(CASE WHEN `t`.`week_dates`='2017-02-14' THEN `t`.`sales_qty` ELSE NULL END) `2017-02-14`,AVG(CASE WHEN `t`.`week_dates`='2017-02-21' THEN `t`.`sales_qty` ELSE NULL END) `2017-02-21`,AVG(CASE WHEN `t`.`week_dates`='2017-02-28' THEN `t`.`sales_qty` ELSE NULL END) `2017-02-28`,AVG(CASE WHEN `t`.`week_dates`='2017-03-07' THEN `t`.`sales_qty` ELSE NULL END) `2017-03-07`,AVG(CASE WHEN `t`.`week_dates`='2017-03-14' THEN `t`.`sales_qty` ELSE NULL END) `2017-03-14`,AVG(CASE WHEN `t`.`week_dates`='2017-03-21' THEN `t`.`sales_qty` ELSE NULL END) `2017-03-21`,AVG(CASE WHEN `t`.`week_dates`='2017-03-28' THEN `t`.`sales_qty` ELSE NULL END) `2017-03-28`,AVG(CASE WHEN `t`.`week_dates`='2017-04-04' THEN `t`.`sales_qty` ELSE NULL END) `2017-04-04`,AVG(CASE WHEN `t`.`week_dates`='2017-04-11' THEN `t`.`sales_qty` ELSE NULL END) `2017-04-11`,AVG(CASE WHEN `t`.`week_dates`='2017-04-18' THEN `t`.`sales_qty` ELSE NULL END) `2017-04-18`,AVG(CASE WHEN `t`.`week_dates`='2017-04-25' THEN `t`.`sales_qty` ELSE NULL END) `2017-04-25`,AVG(CASE WHEN `t`.`week_dates`='2017-05-02' THEN `t`.`sales_qty` ELSE NULL END) `2017-05-02`,AVG(CASE WHEN `t`.`week_dates`='2017-05-09' THEN `t`.`sales_qty` ELSE NULL END) `2017-05-09`,AVG(CASE WHEN `t`.`week_dates`='2017-05-16' THEN `t`.`sales_qty` ELSE NULL END) `2017-05-16`,AVG(CASE WHEN `t`.`week_dates`='2017-05-23' THEN `t`.`sales_qty` ELSE NULL END) `2017-05-23`,AVG(CASE WHEN `t`.`week_dates`='2017-05-30' THEN `t`.`sales_qty` ELSE NULL END) `2017-05-30`,AVG(CASE WHEN `t`.`week_dates`='2017-06-06' THEN `t`.`sales_qty` ELSE NULL END) `2017-06-06`,AVG(CASE WHEN `t`.`week_dates`='2017-06-13' THEN `t`.`sales_qty` ELSE NULL END) `2017-06-13`,AVG(CASE WHEN `t`.`week_dates`='2017-06-20' THEN `t`.`sales_qty` ELSE NULL END) `2017-06-20`,AVG(CASE WHEN `t`.`week_dates`='2017-06-27' THEN `t`.`sales_qty` ELSE NULL END) `2017-06-27`,AVG(CASE WHEN `t`.`week_dates`='2017-07-04' THEN `t`.`sales_qty` ELSE NULL END) `2017-07-04`,AVG(CASE WHEN `t`.`week_dates`='2017-07-11' THEN `t`.`sales_qty` ELSE NULL END) `2017-07-11`,AVG(CASE WHEN `t`.`week_dates`='2017-07-18' THEN `t`.`sales_qty` ELSE NULL END) `2017-07-18`,AVG(CASE WHEN `t`.`week_dates`='2017-07-25' THEN `t`.`sales_qty` ELSE NULL END) `2017-07-25`,AVG(CASE WHEN `t`.`week_dates`='2017-08-01' THEN `t`.`sales_qty` ELSE NULL END) `2017-08-01`,AVG(CASE WHEN `t`.`week_dates`='2017-08-08' THEN `t`.`sales_qty` ELSE NULL END) **`2017M2018-09-05T07:12:37.915727860Z -08-08`**,AVG(CASE WHEN `t`.`week_dates`='2017-08-15' THEN `t`.`sales_qty` ELSE NULL END) `2017-08-15`,AVG(CASE WHEN `t`.`week_dates`='2017-08-22' THEN `t`.`sales_qty` ELSE NULL END) `2017-08-22`,AVG(CASE WHEN `t`.`week_dates`='2017-08-29' THEN `t`.`sales_qty` ELSE NULL END) `2017-08-29`,AVG(CASE WHEN `t`.`week_dates`='2017-09-05' THEN `t`.`sales_qty` ELSE NULL END) `2017-09-05`,AVG(CASE WHEN `t`.`week_dates`='2017-09-12' THEN `t`.`sales_qty` ELSE NULL END) `2017-09-12`,AVG(CASE WHEN `t`.`week_dates`='2017-09-19' THEN `t`.`sales_qty` ELSE NULL END) `2017-09-19`,AVG(CASE WHEN `t`.`week_dates`='2017-09-26' THEN `t`.`sales_qty` ELSE NULL END) `2017-09-26`,AVG(CASE WHEN `t`.`week_dates`='2017-10-03' THEN `t`.`sales_qty` ELSE NULL END) `2017-10-03`,AVG(CASE WHEN `t`.`week_dates`='2017-10-10' THEN `t`.`sales_qty` ELSE NULL END) `2017-10-10`,AVG(CASE WHEN `t`.`week_dates`='2017-10-17' THEN `t`.`sales_qty` ELSE NULL END) `2017-10-17`,AVG(CASE WHEN `t`.`week_dates`='2017-10-24' THEN `t`.`sales_qty` ELSE NULL END) `2017-10-24`,AVG(CASE WHEN `t`.`week_dates`='2017-10-31' THEN `t`.`sales_qty` ELSE NULL END) `2017-10-31`,AVG(CASE WHEN `t`.`week_dates`='2017-11-07' THEN `t`.`sales_qty` ELSE NULL END) `2017-11-07`,AVG(CASE WHEN `t`.`week_dates`='2017-11-14' THEN `t`.`sales_qty` ELSE NULL END) `2017-11-14`,AVG(CASE WHEN `t`.`week_dates`='2017-11-21' THEN `t`.`sales_qty` ELSE NULL END) `2017-11-21`,AVG(CASE WHEN `t`.`week_dates`='2017-11-28' THEN `t`.`sales_qty` ELSE NULL END) `2017-11-28`,AVG(CASE WHEN `t`.`week_dates`='2017-12-05' THEN `t`.`sales_qty` ELSE NULL END) `2017-12-05`,AVG(CASE WHEN `t`.`week_dates`='2017-12-12' THEN `t`.`sales_qty` ELSE NULL END) `2017-12-12`,AVG(CASE WHEN `t`.`week_dates`='2017-12-19' THEN `t`.`sales_qty` ELSE NULL END) `2017-12-19`,AVG(CASE WHEN `t`.`week_dates`='2017-12-26' THEN `t`.`sales_qty` ELSE NULL END) `2017-12-26`,AVG(CASE WHEN `t`.`week_dates`='2018-01-02' THEN `t`.`sales_qty` ELSE NULL END) `2018-01-02`,AVG(CASE WHEN `t`.`week_dates`='2018-01-09' THEN `t`.`sales_qty` ELSE NULL END) `2018-01-09`,AVG(CASE WHEN `t`.`week_dates`='2018-01-16' THEN `t`.`sales_qty` ELSE NULL END) `2018-01-16`,AVG(CASE WHEN `t`.`week_dates`='2018-01-23' THEN `t`.`sales_qty` ELSE NULL END) `2018-01-23`,AVG(CASE WHEN `t`.`week_dates`='2018-01-30' THEN `t`.`sales_qty` ELSE NULL END) `2018-01-30`,AVG(CASE WHEN `t`.`week_dates`='2018-02-06' THEN `t`.`sales_qty` ELSE NULL END) `2018-02-06`,AVG(CASE WHEN `t`.`week_dates`='2018-02-13' THEN `t`.`sales_qty` ELSE NULL END) `2018-02-13`,AVG(CASE WHEN `t`.`week_dates`='2018-02-20' THEN `t`.`sales_qty` ELSE NULL END) `2018-02-20`,AVG(CASE WHEN `t`.`week_dates`='2018-02-27' THEN `t`.`sales_qty` ELSE NULL END) `2018-02-27`,AVG(CASE WHEN `t`.`week_dates`='2018-03-06' THEN `t`.`sales_qty` ELSE NULL END) `2018-03-06`,AVG(CASE WHEN `t`.`week_dates`='2018-03-13' THEN `t`.`sales_qty` ELSE NULL END) `2018-03-13`,AVG(CASE WHEN `t`.`week_dates`='2018-03-20' THEN `t`.`sales_qty` ELSE NULL END) `2018-03-20` FROM `test_table` `t` GROUP BY `t`.`week_dates` ORDER BY `t`.`week_dates` LIMIT 100000

I am simply iterating over set of distinct values to pivot the table, but some random string is being added to the query object. 

Here are the distinct values: ['2014-04-01', '2014-04-08', '2014-04-15', '2014-04-22', '2014-04-29', '2014-05-06', '2014-05-13', '2014-05-20', '2014-05-27', '2014-06-03', '2014-06-10', '2014-06-17', '2014-06-24', '2014-07-01', '2014-07-08', '2014-07-15', '2014-07-22', '2014-07-29', '2014-08-05', '2014-08-12', '2014-08-19', '2014-08-26', '2014-09-02', '2014-09-09', '2014-09-16', '2014-09-23', '2014-09-30', '2014-10-07', '2014-10-14', '2014-10-21', '2014-10-28', '2014-11-04', '2014-11-11', '2014-11-18', '2014-11-25', '2014-12-02', '2014-12-09', '2014-12-16', '2014-12-23', '2014-12-30', '2015-01-06', '2015-01-13', '2015-01-20', '2015-01-27', '2015-02-03', '2015-02-10', '2015-02-17', '2015-02-24', '2015-03-03', '2015-03-10', '2015-03-17', '2015-03-24', '2015-03-31', '2015-04-07', '2015-04-14', '2015-04-21', '2015-04-28', '2015-05-05', '2015-05-12', '2015-05-19', '2015-05-26', '2015-06-02', '2015-06-09', '2015-06-16', '2015-06-23', '2015-06-30', '2015-07-07', '2015-07-14', '2015-07-21', '2015-07-28', '2015-08-04', '2015-08-11', '2015-08-18', '2015-08-25', '2015-09-01', '2015-09-08', '2015-09-15', '2015-09-22', '2015-09-29', '2015-10-06', '2015-10-13', '2015-10-20', '2015-10-27', '2015-11-03', '2015-11-10', '2015-11-17', '2015-11-24', '2015-12-01', '2015-12-08', '2015-12-15', '2015-12-22', '2015-12-29', '2016-01-05', '2016-01-12', '2016-01-19', '2016-01-26', '2016-02-02', '2016-02-09', '2016-02-16', '2016-02-23', '2016-03-01', '2016-03-08', '2016-03-15', '2016-03-22', '2016-03-29', '2016-04-05', '2016-04-12', '2016-04-19', '2016-04-26', '2016-05-03', '2016-05-10', '2016-05-17', '2016-05-24', '2016-05-31', '2016-06-07', '2016-06-14', '2016-06-21', '2016-06-28', '2016-07-05', '2016-07-12', '2016-07-19', '2016-07-26', '2016-08-02', '2016-08-09', '2016-08-16', '2016-08-23', '2016-08-30', '2016-09-06', '2016-09-13', '2016-09-20', '2016-09-27', '2016-10-04', '2016-10-11', '2016-10-18', '2016-10-25', '2016-11-01', '2016-11-08', '2016-11-15', '2016-11-22', '2016-11-29', '2016-12-06', '2016-12-13', '2016-12-20', '2016-12-27', '2017-01-03', '2017-01-10', '2017-01-17', '2017-01-24', '2017-01-31', '2017-02-07', '2017-02-14', '2017-02-21', '2017-02-28', '2017-03-07', '2017-03-14', '2017-03-21', '2017-03-28', '2017-04-04', '2017-04-11', '2017-04-18', '2017-04-25', '2017-05-02', '2017-05-09', '2017-05-16', '2017-05-23', '2017-05-30', '2017-06-06', '2017-06-13', '2017-06-20', '2017-06-27', '2017-07-04', '2017-07-11', '2017-07-18', '2017-07-25', '2017-08-01', '2017-08-08', '2017-08-15', '2017-08-22', '2017-08-29', '2017-09-05', '2017-09-12', '2017-09-19', '2017-09-26', '2017-10-03', '2017-10-10', '2017-10-17', '2017-10-24', '2017-10-31', '2017-11-07', '2017-11-14', '2017-11-21', '2017-11-28', '2017-12-05', '2017-12-12', '2017-12-19', '2017-12-26', '2018-01-02', '2018-01-09', '2018-01-16', '2018-01-23', '2018-01-30', '2018-02-06', '2018-02-13', '2018-02-20', '2018-02-27', '2018-03-06', '2018-03-13', '2018-03-20']

code:
table=Table('test_table',alias='t')
q=MySQLQuery.from_(table)

for value in distinct_values:
	q=q.select(Avg(Case().when(getattr(table,'week_dates')==value,getattr(table,'sales_qty')).else_(None)).as_(value))

PyPika version 0.14.9

**Comment by twheys** [comment]
I tried running the code exactly as you've shared it in 0.14.9 and 0.15.4 and was unable to reproduce. I'm assuming you're passing in `datetime` args? The value that looks corrupted in your query is an alias for the expression it follows, pypika expects an alias to be a string. If you're using `datetime` for `value` in your code sample, I would recommend formatting it as a string before passing it into `as_(...)`. That might resolve your issue.

**Comment by saivarunr** [comment]
Issue was on our side, one of the pipelines corrupted the string, I apologise for this. Thanks!
