### ISSUE TITLE
Is there a way of generating queries with joins across more than two tables?

### ISSUE THREAD

**Issue by csbao** [kayak/pypika#158]
I've tried 

`Query.from_(table1).select('*').join(table2).on('table1key',  'table2key').join(table3).on('table2key', 'table3key')`

but I can see that this is producing something like:
```
SELECT * FROM "table1" 
JOIN "table2" ON "table1"."table1key"="table2"."table2key" AND "table1"."table1key"="table2"."table2key" 
JOIN "table3" ON "table1"."table2key"="table3"."table3key" AND "table1"."table2key"="table3"."table3key"
```
I'm not sure why the duplicates are being produced (`JOIN t2 ON x AND x JOIN t3 on y and y`) 
I'm looking for the generated query to look more like
```
SELECT * FROM "table1" 
JOIN "table2" ON "table1"."table1key"="table2"."table2key"
JOIN "table2"."table2key"="table3"."table3key"
```

Any help is appreciated!

**Comment by twheys** [comment]
Using an equality expression will give you control over which columns to join:

```
Query.from_(table1)
  .select('*')
  .join(table2)
  .on(table1.table1key == table2.table2key)
  .join(table3)
  .on(table2.table2key == table3.table3key)
```

here's the doc reference

**Comment by csbao** [comment]
Perfect, thank you!
