### ISSUE TITLE
copy.deepcopy() takes 55% of runtime of a simple benchmark

### ISSUE THREAD

**Issue by grigi** [kayak/pypika#160]
Hi, we are working on [Tortoise ORM](https://github.com/tortoise/tortoise-orm) and I did a series of simple benchmarks to start finding performance bottlenecks. In the one transactioned insert test:
https://github.com/tortoise/orm-benchmarks#interesting-profiling-results
I found that `copy.deepcopy()` takes ~55% of the runtime. Changing it to `copy.copy()` gives me an 83% speed up in that particular test.

Of course it is there for a reason as without it we can get unexpected side-effects, such as what the `pypika.tests.test_joins.JoinBehaviorTests.test_immutable__queries_after_join` test determines.

I'm just wondering what can we do to speed this up?

**Comment by twheys** [comment]
Deepcopy could be replaced with a more comprehensive implementation of `__copy__` in the `QueryBuilder` class. Can you try using the changes in my PR in your benchmark and let me know if you see a similar improvement?

**Comment by grigi** [comment]
Thanks @twheys 
I did the test and got a 53% speedup in that particular benchmark.
Thank you, this is a big gain :+1:

**Comment by twheys** [comment]
Is that sufficient? Could probably try and optimize a bit better. The copies are used to keep the queries immutable.
