### ISSUE TITLE
setup.py encoding problem (conda package)

### ISSUE THREAD

**Issue by Winand** [kayak/pypika#165]
I've tried to build a conda (4.5.11) package and got the following error
```
  File "setup.py", line 1
SyntaxError: encoding problem: utf8
```
Maybe 'utf-8' is needed? see [a comment](https://github.com/saghul/pycares/issues/19#issuecomment-132499313)

**Comment by twheys** [comment]
Could you please check out this PR and let me know if it resolves your issue? If it does not, could you please get me a list of instructions of how to reproduce?

https://github.com/kayak/pypika/pull/166

**Comment by Winand** [comment]
Thanks. I'll check as soon as I understand how to build a conda package from source (not from pypi hosted package)

**Comment by Winand** [comment]
I was wrong. `patch` command works as expected. Then `python setup.py install` (python version is 3.6.6 conda forge) is run and fails with encoding problem. I modified source code to pause before this command, patched setup.py manually and continued the process. It helped.

That's strange but when I run `python setup.py install` manually it doesn't complain about 'utf8'.

@twheys anyway I assume that this patch fixes the problem
