### ISSUE TITLE
Extraneous quotes when using passing Field to between

### ISSUE THREAD

**Issue by DGalt** [kayak/pypika#168]
[System Environment]

Windows 10
Python: 3.6.4
PyPika: 0.15.7

[Overview]
When doing a join based on a table field's value being between values derived from another field (or set of fields), the `start` and `end` portions get wrapped in quotes. 

```
t1 = Table('Table1', alias='t1')
t2 = Table('Table2', alias='t2')

Query.from_(t1).join(t2).on(t1.Value.between(t2.Start, t2.End)).select(t1.value).get_sql()
```

yields:

`'SELECT t1.value FROM Table1 t1 JOIN Table2 t2 ON t1.Value BETWEEN "t2"."Start" AND "t2"."End"'`

Looking at `BetweenCriterion` it seems like, if `self.start` and/or `self.stop` are instances of `Term` then `get_sql(**kwargs)` should be called (as is done with `self.term`). Unless this is intended behavior?

**Comment by twheys** [comment]
actually the intended behavior is that quotes are always used, in case you use a reserved word or special character like a space in a name. `get_sql` isn't meant to be called directly, unless you pass in some arguments. You should prefer to use `str(query)` instead.  However, since the default quote character for `get_sql` is `None`, that should respected in the entire query. Looks like in your case the arguments for BETWEEN are getting passed a quote character when rendering as a string. I'll take a look.

**Comment by DGalt** [comment]
Oh, interesting. So, the reason I've been using `get_sql` is that when I just wrap the query with `str()`, if I'm specifying a schema the resulting SQL is invalid. 

So, for example (pseduo-tables):

```
t1 = Table('Table1', schema='DB.dbo', alias='t1')
str(Query.from_(t1).select(t1.star))
```

generates:

`'SELECT "t1".* FROM "DB.dbo"."Table1" "t1"'

Which, when trying to execute results in:
DatabaseError: Execution failed on sql `'SELECT "t1".* FROM "DB.dbo"."Table1" "t1"': ('42S02', "[42S02] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid object name 'DB.dbo.Table1'. (208) (SQLExecDirectW)")

Whereas calling `get_sql()`: 

`Query.from_(t1).select(t1.star).get_sql()`

generates: 
`'SELECT t1.* FROM DB.dbo.Table1 t1'`

which executes just fine.

**Comment by twheys** [comment]
I suppose the issue is the schema. I've never tested pypika with SQL server and not familiar with the specifics of it. Can you omit the `DB.` part of the schema name? Would it be correct to wrap each part of the schema name like `"DB"."dbo"."Table1"`?

**Comment by twheys** [comment]
Reopening to address schema formatting issue

**Comment by DGalt** [comment]
Yes, wrapping the individual elements in quotes separately executes correctly.
