### ISSUE TITLE
SQLite boolean casting

### ISSUE THREAD

**Issue by Zeliboba5** [kayak/pypika#171]
SQLite doesn't have `FALSE` and `TRUE` literals, so when you passing `bool` value to PyPika it wraps it as `false` or `true` which leads to error in SQLite.

I understand that PyPika isn't obliged to encapsulate dialects features, but I still think that it should be implemented in PyPika so that same queries would work if you just change dialect of query builder.

Looking at the code - I couldn't come up with easy solution for it with current code. Problem is ValueWrapper is completely independent of QueryBuilder and there is no way to substitute ValueWrapper with custom value wrapper for custom dialect.

Is there some way to do it easily that I am not seeing or it have to done by binding value wrapper to query builder and overriding it in custom dialects?

**Comment by twheys** [comment]
PyPika does have some support for vendor specific SQL dialects, so it wouldn't be trouble to support this too. I'm guessing that the ValueWrapper should replace `True` and `False` literals in SQL lite with `1` and `0`, respectively?

**Comment by Zeliboba5** [comment]
Yeah, the reason why it is issue and not PR is that as I see current `ValueWrapper` has no easy way to change it's behaviour based on dialect of `QueryBuilder`
