### ISSUE TITLE
JOIN on multiple conditions

### ISSUE THREAD

**Issue by timbarkerSE** [kayak/pypika#172]
Hi. I coudn't see in the docs but Is there a way to join to a table on multiple conditions as follows:

`JOIN base_imagehashtag ON base_image.id = base_imagehashtag.image_id AND base_imagehashtag.hashtag_id IN (13,20)`

Thanks a lot.

**Comment by twheys** [comment]
Yes, similar to a join with one condition

```
history, customers = Tables('history', 'customers')
q = Query.from_(history).join(
    customers
).on(
    (history.customer_id == customers.id) & (history.company_id == customers.company_id)
) ... 
```

The parentheses around the equals expressions are necessary because the python order of operations evaluates `&` before `==`.

**Comment by timbarkerSE** [comment]
I cannot thank you enough for telling me this and your quick response!

**Comment by twheys** [comment]
happy to help 👍
