### ISSUE TITLE
on_duplicate_key_update resolves in TypeError: 'Field' object is not callable

### ISSUE THREAD

**Issue by jspoe** [kayak/pypika#173]
Not sure if i'm doing something wrong, but it i'm hitting "TypeError: 'Field' object is not callable" while using on_duplicate_key_update with the example provided for it.

`
from pypika import Query, Table
from pypika.terms import Values

table = Table('config')
key = 'key'
value = 'a value'

q = Query.into(table)\
.columns(table.key, table.value)\
.insert(key, value)\
.on_duplicate_key_update(table.value, Values(value))
`

When I ommit the on_duplicate_key_update call it's working fine.
When I ommit the Values() call, it gives the same error.

**Comment by mikeengland** [comment]
Hi @jspoe 

If you import the MySQLQuery class instead of just Query, it should work. Let me know how you get on.

**Comment by jspoe** [comment]
@mikeengland Ah I see, working now indeed, thanks!

**Comment by houjincheng1992** [comment]
Well i also have the same problem, it work indeed, thanks!

**Comment by tina0430** [comment]
Hi, I import the  MySQLQuery class but it dose not work.

This is my code

from pypika import MySQLQuery as Query, Table, functions as fn
addr = '%경기도%'
    date = '2019/01/01'
    mall = Table('descent_onlinemall', schema='yoonah')
    query = Query.from_(mall)
    query = query.where(mall.index_num.isin(
        **mall.select(mall.index_num).where(mall.address_short.like(addr)).where(mall.order_date > date)))**
    query = query.select(mall.address_short, fn.Sum(mall.quantity))
    query = query.groupby(mall.address_short)

TypeError occurred at the bold line.

The error message is 'TypeError: 'Field' object is not callable'

Thank you.
