### ISSUE TITLE
Is there a way to unselect columns from a query?

### ISSUE THREAD

**Issue by csbao** [kayak/pypika#174]
Say I have a QueryBuilder object that was constructed using
`Query.from_("example_table").select("a", "b", "c")`

If I later, given some condition, wanted to unselect some or all of the columns currently in that `QueryBuilder` object, is there a way to do this?

Thanks!

**Comment by twheys** [comment]
No, but the queries are immutable, so you could branch out into multiple query builder objects:

```
query = Query.from_("example_table").select("a", "b")
query_with_c = query.select("c")
```
