### ISSUE TITLE
CTE Support

### ISSUE THREAD

**Issue by alfredr** [kayak/pypika#178]
I need CTE support. If there is a preferred path to implementation I'm happy to work in that direction on the hopes that you'll accept a pull request. Is this something that you would be willing to accept a patch for?

**Comment by twheys** [comment]
I believe it is already implemented. Check this unit test for an example https://github.com/kayak/pypika/blob/master/pypika/tests/test_selects.py#L767

**Comment by alfredr** [comment]
Yeah this should work for me. My apologies, I'm not sure how I overlooked it.
