### ISSUE TITLE
Subquery as select field

### ISSUE THREAD

**Issue by sinitsynsv** [kayak/pypika#180]
Is it possible to use subquery in the select clause? Something like this
```sql
SELECT
  table_a.id,
  table_a.name,
  (
    SELECT table_b.name
    FROM table_b
    WHERE
      table_b.id=table_a.id_table_b
  )
FROM table_a
```

**Comment by twheys** [comment]
Thought it would be but wrote some tests to check it and found a bug. I've opened a PR, which will fix it. You can reference the test cases for an example. https://github.com/kayak/pypika/pull/181/files#diff-a89ffcd508c44b98b03f87c220cf4d38R671
