### ISSUE TITLE
Add Join type examples on Documentation

### ISSUE THREAD

**Issue by gonzalezzfelipe** [kayak/pypika#190]
I had a hard time founding an example to making a simple left join, I ended up looking for it on the tests.

**Comment by twheys** [comment]
https://pypika.readthedocs.io/en/latest/2_tutorial.html#joining-tables-and-subqueries

Do you mean to set the join type to be a left join as opposed to an inner join?

**Comment by gonzalezzfelipe** [comment]
Thanks for the answer, yes I mean exactly that. I meant to do a left join, and couldn't find any example of how it was done. I ended up looking for them on the tests.
