### ISSUE TITLE
Import structure from sql conexion

### ISSUE THREAD

**Issue by DiegoFern** [kayak/pypika#195]
Is it possible in some way import the a object which represent the DB which avoid wrong fields?

For example if the conexion has the tables customer and prices: 
```
A=ImportDB(con)
dir(A)
>[...,''price',"customer"]
>A.prices.cost#field cost of price
>A.prices.cots#this field doesn't exists and it will be break down when the query is made
```

**Comment by twheys** [comment]
This would be difficult to support since different database vendors have different syntax for getting the table structure and different syntax for how they display that structure.
