### ISSUE TITLE
Add EmptyCriterion for easier generic queries

### ISSUE THREAD

**Issue by abondar** [kayak/pypika#196]
There are cases when you are building query complex criterion based on some external checks.
And in those cases you could want to have some empty criterion to build you complex criterion from it.

Basic case, where you have dict of argument and want to have any corresponding rows, could look like this:
```
criterion = EmptyCriterion()

for key, value in filters.items():
    criterion |= (table.key == value)

query = query.where(criterion)
```

Which right now would look like this:
```
criterion = None

for key, value in filters.items():
    if not criterion:
        criterion = (table.key == value)
    else:
        criterion |= (table.key == value)

if criterion:
    query = query.where(criterion) 
```

Also, there could be more complex cases where you got two criterions from some generic functions, and there you would have to do:
```
if not criterion1 and criterion2:
    res_criterion = criterion2
elif criterion1 and not criterion2:
    res_criterion = criterion1
else:
   res_criterion = criterion1 | criterion2
```
While, if functions could return EmptyCriterion, you could just do:
```
res_criterion = criterion1 | criterion2
```

Does this seem like good idea for you? If you approve this design I could try implementing it

**Comment by twheys** [comment]
Would the following syntax work for you?

```
criterion = Criterion.or_(table.key == value
                          for key, value in filters.items())
query = query.where(criterion)
```

**Comment by twheys** [comment]
Nevermind that question. After playing around for a minute with it, it seemed that an empty criterion could also be a useful construct to have, and was useful for implementing `any` and `all`  functions. It was a small addition, so I threw together a PR for it real quick. Mind taking a look at the changes?

**Comment by nikkitha92** [comment]
Hi twheys, 
i tried the same code as yours. However the key values arent reflecting.

SELECT "user_id","name","age" FROM "final_table_vr" WHERE "key"='budweiser' OR "key"='30-35' OR "key"='Male'
