### ISSUE TITLE
Mysqlquery does not give semicolon

### ISSUE THREAD

**Issue by ehdgua01** [kayak/pypika#203]

**Comment by x8lucas8x** [comment]
@ehdgua01 please be more specific. Provide version and code to reproduce the issue.

**Comment by ehdgua01** [comment]
i'm using 0.21.0 version
```
q = MySQLQuery.into(table) \
    .columns(*keys) \
    .insert(*values) \

for idx, key in enumerate(keys):
    q = q.on_duplicate_key_update(key, values[idx])

q.get_sql(quote_char='`')
```
return query without semi colon so mysql error on execute query

**Comment by twheys** [comment]
@ehdgua01 no pypika does not add a semicolon. How are you executing the query on mysql, what error are you getting?

**Comment by ehdgua01** [comment]
I execute with a query which i receive from pypika.
mysql trigger syntax - missing semi colon

**Comment by mikeengland** [comment]
@ehdgua01 - how are you executing the query? Please can you provide sample code?

**Comment by ehdgua01** [comment]
python code
```
def make_query(table: str, keys: tuple, values: tuple)
    table = Table(table)

    if not values or len(keys) != len(values):
        return None

    q = MySQLQuery.into(table) \
        .columns(*keys) \
        .insert(*values) \

    for idx, key in enumerate(keys):
        q = q.on_duplicate_key_update(key, values[idx])

    return q.get_sql(quote_char='`')

with open(SQL_PATH, 'w') as f:
    f.write(make_query(table='server', keys=('identifier', 'name'), values=(identifier, name)))
```

shell command
```
mysql -u username -ppassword database < SQL_PATH
```

mysql trigger syntax - missing semi colon. 💣
but now this problem was solved.
I was just curious because pypika didn't give me a semicolon.

**Comment by mikeengland** [comment]
Ok. I would recommend using a MySQL module like https://github.com/PyMySQL/PyMySQL or https://dev.mysql.com/doc/connector-python/en/ instead of writing the SQL to a file and executing it on the shell (unless there is good reason for doing it that way). When using these modules, you do not need to worry about semi colons. 

I will close this issue now.

**Comment by ehdgua01** [comment]
thank you
