### ISSUE TITLE
Fetching Query data

### ISSUE THREAD

**Issue by kfk** [kayak/pypika#209]
I have a running Query with Pypika and I keep adding elements to it like where, groupby, etc.

I have noticed that in some cases it would be very convenient to be able to get Table/s, Fields and other pypika objects from a pypika Query object.

For instance, if I have a running query on the 'history' table, I would be able to do:

history = q.Tables['history']

and that would give me back the Table('history') object.

In the query below, I would be able to add the join to the 'customers' table directly on top of the running query that already includes the 'history' table.

`history, customers = Tables('history', 'customers')
q = Query.from_(history).join(
    customers
).on(
    history.customer_id == customers.id
).select(
    history.star
).where(
    customers.id == 5
)`

**Comment by twheys** [comment]
In your code, you can set some values on the query itself like
```
q = Query.from_(history)
  .join( customers ).on( history.customer_id == customers.id ) \
  .select( history.star ) \
  .where( customers.id == 5 )
q.Tables = {
  'History': history,
}
```
That would handle your use case.
