### ISSUE TITLE
Postgresql casts

### ISSUE THREAD

**Issue by feribg** [kayak/pypika#210]
I was wondering if it's possible to select using a cast with the table syntax:

```
q = Query.from_(customers).select(customers.id, customers.fname, customers.lname, customers.phone)
```

to be something like

```
SELECT customers.phone::phone FROM customers
```

Thanks!

**Comment by espositofulvio** [comment]
that is postgresql syntax for casting, which you can achive with the more standard 'cast( customers.phone as phone)' function, which is supported in pypika, AFAIK. Something along the line of:

```sql
from pypika.functions import Cast
q = Query.from_(customers).select(
    customers.id, 
    customers.fname, 
    customers.lname, 
    Cast( customers.phone, 'phone')
)
```
