### ISSUE TITLE
Oracle SQL limit syntax is wrong

### ISSUE THREAD

**Issue by Spenhouet** [kayak/pypika#211]
If I want that only x entries will be returned then I could use `.limit(x)` but for Oracle the syntax isn't correct.

Using `OracleQuery` and `.limit(2)` results in

`'SELECT * FROM "table" LIMIT 2'`

but that doesn't work in Oracle DB.

Correct would be:

`'SELECT * FROM "table" WHERE ROWNUM <= 2'`

**Comment by twheys** [comment]
Hi, would prefer to try to avoid translating the same queries to different dialects. What we could do is give a constant that you can use in place.  Something like `Query...where(ROWNUM <= 2)`. This would match the oracle syntax better, as well. What do you think?

**Comment by Spenhouet** [comment]
While I would be happy with any fix I feel like what is the sense behind `OracleQuery` if the methods don't adapt to the correct database syntax?

**Comment by twheys** [comment]
The goal of pypika is not to map a common syntax to multiple DB platforms, but rather to provide a syntax that wraps the SQL you would be writing without it.

**Comment by Spenhouet** [comment]
Then where is the value added compared to just directly writing SQL?

_Side note: We switched to ponyORM since it fully supports Oracle and also works in a really pythonic way._

**Comment by twheys** [comment]
This pseudocolumn is available her https://github.com/kayak/pypika/blob/master/pypika/pseudocolumns.py#L6

The following code snippet is an example of how it can be used.

```
from pypika.pseudocolumns import RowNum
OracleQuery
    ...
    .where(RowNum > limit)

```
