### ISSUE TITLE
Allow filtering by non existant table

### ISSUE THREAD

**Issue by jtrain** [kayak/pypika#227]
When creating a subquery, often I'd like to reference the parent table id.
However this validation code https://github.com/kayak/pypika/blob/master/pypika/queries.py#L718 prevents that.

For a contrived example

```
Teacher, School = Tables("teacher", "school")
Query.from_(School).select(
 Query.from_(Teacher).select(Teacher.name).where(
  Teacher.current_school_id==School.id
  ).limit(1).as_('a_teacher')
)
```

Here Teacher is referencing the parent 'School' table and the validation would fail.

My use case is generally including a JSONB array of tags or similar from the result of a subquery in the parent.

I have worked around this by adding the table, filtering the subquery, then removing the table. Kind of like a decorate / action / undecorate pattern.

Options I can think of for solving this:
1. A flag that would disable this particular validation check (but still allow others);
2. An API for a validations framework where validations can be added and removed;
3. A way of telling a subquery about a known table, that would pass this validation and have no effect on output SQL otherwise; and
4. Continue the decorate / action /undecorate pattern in our code.

I'm happy to develop a PR if any of these, or another option excites you.

**Comment by twheys** [comment]
Appreciate the suggestions. Might be beneficial to have configurable validation, but in most cases pypika avoids any sort of validation, leaving that to the database itself. In this case, it might be that pypika needs to reference something in the table, so it enforces that the table is actually selected from. This is a case that isn't considered, but the subquery does know it's a subquery when the SQL is being generated.

Maybe as a short term solution we could take the first option and make the `where` function accept a kwarg to disable the validation?

**Comment by jtrain** [comment]
Sure I'll take a look, and see what feels good.

**Comment by jtrain** [comment]
#228 An approach for fixing this, other approaches could easily be taken if that wasn't the best trade off
