### ISSUE TITLE
Group by alias from SQL Extract

### ISSUE THREAD

**Issue by timbarkerSE** [kayak/pypika#232]
I'm trying to select some data using the extract function as follows:

`.select(
            fn.Extract('ISODOW', 'to_timestamp(base_image.created)::date', 'dayofweek')
        ).groupby(
            'dayofweek'
        )`

In some cases I need to join this query to another table and when that happens the group by clause outputs SQL as 

 `GROUP BY base_image.dayofweek`

(where base_image is the base table in the query). 
However, 'dayofweek' is an alias and should remain unprefixed. Is there some way to stop it prefixing the group by term?

Thanks!

**Comment by twheys** [comment]
pypika will do this for you automatically if you use a database that supports it, ie not MSSQL
```
my_field = fn.Extract('ISODOW', 'to_timestamp(base_image.created)::date').as_('dayofweek')
query = ... \
   .select(my_field) \
   .groupby(my_field)
```

**Comment by timbarkerSE** [comment]
Thanks so much.

**Comment by timbarkerSE** [comment]
I don't know if you'll see this as the issue is closed but in a related query I need to get the full date (also converting from unix timestamp) as opposed to the day of week. It seems like I need something like the following but the 'to_timestamp' part gets output as a string in quotes. 

`my_field = fn.Cast('to_timestamp(base_image.created)', 'date').as_('dayofweek')`
`            query = query.select(
                my_field
            ).groupby(
                my_field
            )`

Thanks again
