### ISSUE TITLE
Is it possible to find not NULL column?

### ISSUE THREAD

**Issue by Yankee-by** [kayak/pypika#233]
I am going to realize something like that: 
`SELECT * FROM country WHERE "housing" is not NULL`

Can you help with it?

**Comment by twheys** [comment]
```
table = Table( ... )
query = Query.from_(table).select('*').where(table.housing.notnull())
```

**Comment by dashmug** [comment]
@twheys `notnull()` is giving me the wrong query.

```
table = Table("Houses")
query = Query.from_(table).select("*").where(table.housing.notnull())
```

outputs the following
```
SELECT * FROM "Houses" WHERE NOT "housing" IS NULL
```

**Comment by amundeep** [comment]
Getting the same error as @dashmug above.  I am trying to write "is not null" as well, is there any workaround for this at the moment?

**Comment by zmunro** [comment]
I have a hacky workaround:
```python
table = Table("Houses")
query = Query.from_(table).select("*").where(table.housing.notnull())
query_string = query.get_sql().replace('"housing" IS NULL', '"housing" IS NOT NULL')
```
But yeah, this is a blatant bug that needs to be fixed ASAP

**Comment by zmunro** [comment]
This shouldn't make a difference. `NOT (foo IS NULL)` and `foo IS NOT NULL` should return the same thing. The parentheses are only added for the sake of clarity, but are not necessary I believe.

**Comment by zmunro** [comment]
You can run a query like this to check and see it returns nothing:
```sql
(select housing from Houses where not housing is null)
intersect
(select housing from Houses where housing is not null);
```
