### ISSUE TITLE
How is the key of isin turned into a variable

### ISSUE THREAD

**Issue by qianxuanyon** [kayak/pypika#239]
![image](https://user-images.githubusercontent.com/29041881/55306911-651a0400-5488-11e9-8853-3f24e7b78d9c.png)
How to achieve

**Comment by mikeengland** [comment]
HI @qianxuanyon!

The docs have the following example:

Query.from_(self.table_abc) \
        .select(self.table_abc.foo, self.table_abc.bar) \
        .where(Tuple(self.table_abc.foo, self.table_abc.bar).isin([(1, 1), (2, 2), (3, 3)]))

results in:
SELECT "foo","bar" FROM "abc" WHERE ("foo","bar") IN ((1,1),(2,2),(3,3))

Does this help?

**Comment by qianxuanyon** [comment]
> HI @ qianxuanyon！
> 
> 文档有以下示例：
> 
> Query.from_（self.table_abc）
> .select（self.table_abc.foo，self.table_abc.bar）
> .where（Tuple（self.table_abc.foo，self.table_abc.bar）.isin（[（1,1）， （2,2），（3,3）]））
> 
> 结果：
> SELECT“foo”，“bar”FROM“abc”WHERE（“foo”，“bar”）IN（（1,1），（2,2），（3,3））
> 
> 这有帮助吗？如果没有，请你描述一下你想要的结果吗？
![image](https://user-images.githubusercontent.com/29041881/55310354-db236880-5492-11e9-854c-01ac62d8b046.png)

Already successful thanks
Using the Field object
