### ISSUE TITLE
Support for Raw statements

### ISSUE THREAD

**Issue by blitzd** [kayak/pypika#244]
I'm looking to find if PyPika can somehow support raw SQL statements, something similar to how Knex.js has their `raw` support here:

https://knexjs.org/#Builder-whereRaw

My specific issue is that I have a query on PostgreSQL where I need to specify the timezone for a datetime comparison, and I don't see any way to do that within the existing functionality.

SQL Syntax would be similar to this:

```
WHERE UPPER(billing_detail_city) IN %s
                    AND time AT TIME ZONE 'America/Toronto' >= %s
                    AND time AT TIME ZONE 'America/Toronto' <= %s
                    AND sku LIKE 'MM%%';
```
I've tried implementing it as a Criterion, but I don't know if that is the proper way, and I'm also finding that my version doesn't work within a `where` with the `&` syntax.

```Python
class Timezone(Criterion):
    def __init__(self, term, timezone, alias=None, *args, **kwargs):
        super().__init__(alias)
        self.term = term
        self.timezone = timezone
        self.alias = alias

    def fields(self):
        return []

    def get_sql(self, **kwargs):
        if self.alias:
            return f'{self.term} AT TIME ZONE \'{self.timezone}\' AS {self.alias}'
        else:
            return f'{self.term} AT TIME ZONE \'{self.timezone}\' '
```
This works:

```Python
                q = detail_query.where(
                    (Upper(order.billing_detail_city)).isin(cities) &
                    order_item.sku.like('MM%') &
                    Timezone(order.time, timezone='America/Toronto') >= dateutil.parser.parse(args.date)
                )

                q = q.where(
                    Timezone(order.time, timezone='America/Toronto') < dateutil.parser.parse(args.cutoff_date)
                )
```

... But this:

```Python
                q = detail_query.where(
                    (Upper(order.billing_detail_city)).isin(cities) &
                    order_item.sku.like('MM%') &
                    Timezone(order.time, timezone='America/Toronto') >= dateutil.parser.parse(args.date) &
                    Timezone(order.time, timezone='America/Toronto') < dateutil.parser.parse(args.cutoff_date)
                )
```

Produces:

`TypeError: unsupported operand type(s) for &: 'datetime.datetime' and 'Timezone'`

**Comment by twheys** [comment]
The ´&´ character in python has precedence over the comparator characters. You'll need to wrap the expressions in params in order to override the order of operations. Try this

´´´
                q = detail_query.where(
                    (Upper(order.billing_detail_city)).isin(cities) &
                    order_item.sku.like('MM%') &
                    (Timezone(order.time, timezone='America/Toronto') >= dateutil.parser.parse(args.date)) &
                    (Timezone(order.time, timezone='America/Toronto') < dateutil.parser.parse(args.cutoff_date))
                )
´´´
