### ISSUE TITLE
Support for Big Quqery syntax

### ISSUE THREAD

**Issue by ralbertazzi** [kayak/pypika#246]
Is there any support for the nested schema structure `table.field.sub_field` used in Google BigQuery?

This obviously doesn't work:
```
customers = Table('customers')
q = Query.from_(customers).select(customers.field.sub_field)
```

**Comment by twheys** [comment]
Hi, if you could please provide some examples of the SQL you are trying to produce and the pypika syntax you would like to use, it would be possible to implement it.

**Comment by ralbertazzi** [comment]
Given a table schema like the following one:
```
field_1
field_2
nested_field_1.field_3
nested_field_1.field_4
nested_field_2.field_5
nested_field_2.field_6
```

I'd like to do the following:
```
SELECT field_1, field_2, nested_field_1.field_4, nested_field_2.*
FROM table
```

As you can see you can either:
* Select a plain field: `SELECT field_1`
* Select a plain field inside a nested field: `SELECT nested_field_1.field_1`. It will be called `field_1` in the output result table
* Select all fields inside a nested field: `SELECT nested_field_2.*`. All fields will be selected, and they won't have the prefix `nested_field_2.` in the output result table
* Select all fields `SELECT *`. Schema will be the same (meaning that prefixes will be kept)

I was thinking if it was possible to do something like:
```
Query.from_(customers).select(customers["field.sub_field"])
```

**Comment by luiztauffer** [comment]
Hi, thanks for the great work on this library, it's already helping me a lot!
I'm having annoying problems with google BigQuery though, mostly for quotes `""` and alike.
For example, the produced query string needs to have it's quotes removed with
```python
query.replace('"', '')
``` 
The table path also needs to be put between backquotes ` `` ` 

Thought this info would be useful for anyone using PyPika qith Google BigQuery

**Comment by iobruno** [comment]
@luiztauffer I'm kinda late here, but just to keep it for later reference:

```python
query: QueryBuilder = Query.from_(tbl_name).select( ... )
query_string = query.get_sql(quote_char=None)
```

So you can just throw query_string for BigQuery to run
