### ISSUE TITLE
Join the same table twice. Documentation needed?

### ISSUE THREAD

**Issue by bikeshedder** [kayak/pypika#248]
Let's assume I have two tables `Person` and `Friendship`. Now I want to fetch all friendships including the person data. I figured an alias will do the trick and found the following code to work exactly like I needed it:

```python
person_a = Table('person', alias='person_a')
person_b = Table('person', alias='person_b')
friendship = Table('friendship')
query = (Query
    .from_(friendship)
    .join(person_a).on(friendship.person_a_id == person_a.id)
    .join(person_b).on(friendship.person_b_id == person_b.id)
    .select(friendship.id, person_a.id, person_a.name, person_b.id, person_b.name)
)
```

This produces the query I'm expecting:

```sql
SELECT
    "friendship"."id",
    "person_a"."id", "person_a"."name",
    "person_b"."id", "person_b"."name"
FROM "friendship"
JOIN "person" "person_a" ON "friendship"."person_a_id"="person_a"."id"
JOIN "person" "person_b" ON "friendship"."person_b_id"="person_b"."id"
```

I wonder if this is the correct (and only?) way of doing it. Big kudos on the API design. If this really is the way to go it is very intuitive. It just needs a small example in the documentation, I think.

**Comment by twheys** [comment]
Yes, that's exactly right. I think this is a bit specific to document it on readthedocs, but this ticket serves as documentation as well. In pypika, the alias acts as an identifier, so even if you join the same table multiple times, pypika can distinguish which table you want to use based on the alias set in your instance of table.
