### ISSUE TITLE
Possible incorrect parenthesization of scalar subqueries.

### ISSUE THREAD

**Issue by alfredr** [kayak/pypika#249]
There seems to be some issue using scalar sub-queries as arguments. For example:

```python
from pypika import Query, terms as ts
Query.select(ts.Mod(5, Query.select(4)))
```
outputs
```sql
SELECT MOD(5,SELECT 4)
```

Which, at a minimum, gives Postgres heartburn.
```
> SELECT MOD(5,SELECT 4);
ERROR:  syntax error at or near "SELECT"
LINE 1: SELECT MOD(5,SELECT 4);
```

However the following query is valid:
```
> SELECT MOD(5,(SELECT 4));
 mod
-----
   1
(1 row)
```

I am unsure if such queries are standard, but I suspect that adding the extra parentheses won't hurt anything that already works, and more queries will work on Postgres.

**Comment by twheys** [comment]
not sure what the result would be, but try:
```
from pypika import Query, terms as ts
Query.select(ts.Mod(5, (Query.select(4),)))
```
Wrapping your query in a tuple like you want in the results should produce the desired output.
