### ISSUE TITLE
Set difference, set intersection support?

### ISSUE THREAD

**Issue by roger-rojas** [kayak/pypika#250]
Is there existing/planned support for set difference or set intersection operators?

e.g. in table "Likes" with columns "Person" and "Pizza":
1) To find people who like _both_ mushroom and onion pizza
SELECT person FROM likes WHERE pizza="mushrooms"
INTERSECT
SELECT person FROM likes WHERE pizza="onions"

2) To find people who like onions _but not_ ham on their pizzas
SELECT person FROM likes WHERE pizza="onions"
MINUS
SELECT person FROM likes WHERE pizza="ham"

I am new to SQL, so maybe there is a similarly simple way to do this, but set operations make these clear.

**Comment by twheys** [comment]
I think this could be implemented in pypika pretty easily, since we have code already for things like unions that produce similar SQL. Would you like to try and raise a PR?

**Comment by DimpleK26** [comment]
@twheys I have raised a PR regarding the above issue. Could you please take a look

**Comment by roger-rojas** [comment]
Wow, thank you @DimpleK26 ! I'm pretty inexperienced with the workflow on here. Now that your changes have been merged, do I go ahead and click "Close Issue"?

**Comment by DimpleKannadasan** [comment]
@roger-rojas Yes . If you are happy with intersect ,minus and except operations, kindly go ahead :)
