### ISSUE TITLE
pypika.functions.NullIf creates SQL with syntax error

### ISSUE THREAD

**Issue by akmiller01** [kayak/pypika#253]
From your tests, the Null If function returns `SELECT NULLIF("foo"=0) FROM "abc"` which throws a syntax error when you put it into PostgreSQL:

```
postgres=# SELECT NULLIF("foo"=0) from "abc";
ERROR:  syntax error at or near ")"
LINE 1: SELECT NULLIF("foo"=0) from "abc";
```

Haven't tested across all SQL platforms, but it needs a comma instead of an equal sign.

Suggested fix PR here: https://github.com/kayak/pypika/pull/252

**Comment by twheys** [comment]
Fixed by #252
