### ISSUE TITLE
Create Table

### ISSUE THREAD

**Issue by kfk** [kayak/pypika#255]
Hello, I am looking into Pypika to replace our alteryx in-db workflows, so far it's working very well. It seems, however, that Pypika does not support create table? Normally, after transforming the data inside the database (group by, filters, joins, etc.), we save it back inside a db table.

I would also be ok to roll out my own create table solution, but could you give me some directions? The main issue is going to be column types. We need to create a table with the same column types as the final selected columns.

EDIT. I see that I can extend pypika extending the Function class inside .terms, any docs on this? Or could you give me a couple of tips? I am guessing I could create a pypika function to do this.

**Comment by twheys** [comment]
Hi, we have implemented this, and it's pretty different from database to database, so it would be a challenge.

I would recommend implemented in parallel to the `queries` module. Not sure how much code it could share with the query builders, it would need to be it's own thing.

I don't have any specific preferences on how it should be implemented, as long as it follows similar patterns to the existing code. For vendor specific code, you can follow the same patterns as we do for queries, for example if you look at `MySQLQuery` you can see there's parts to the queries that only make sense for MySQL.

**Comment by sabrikaragonen** [comment]
@twheys if you have implemented it, can you please share what you have until now? Maybe we can contribute it and can add it to package.

**Comment by RobinPapke** [comment]
@sabrikaragonen there are a some tests in https://github.com/kayak/pypika/blob/master/pypika/tests/test_create.py#L30 that show how to create a table using select. You can find the actual implementation in https://github.com/kayak/pypika/blob/master/pypika/queries.py#L1366
