### ISSUE TITLE
cannot place limit on update query mySQL

### ISSUE THREAD

**Issue by maciek-d** [kayak/pypika#259]
am trying to place a limit on an update query in pypika.

```
MySQLQuery.update(conversations).set(
            conversations.text, text).limit(1)
```
When I print the query I get
```
UPDATE `TEST_conversations` SET `text`=245
```
Is there any way I can set a limit on an update query in pypika??

**Comment by twheys** [comment]
This would need to be added. Are you able to raise a PR?

**Comment by mikeengland** [comment]
@maciek-d This should now be fixed in the above merged PR.
