### ISSUE TITLE
Reverse IN operator?

### ISSUE THREAD

**Issue by rossjrw** [kayak/pypika#263]
Say I have a selection query and want to add the following condition to it:

```sql
WHERE 'John Doe' IN (
    SELECT author FROM art_au
    WHERE article_id=art.id
)
```

Note that I'm looking for a static value in the result of a subquery (rather than looking for a value from another selection).

Existing syntax would suggest that this is the correct option:

```python
subq = Query.from_(art_au).select(art_au.author).where(
    art_au.article_id == art.id
)
query = query.where('John Doe'.isin(subq))
```

But of course, `str` has no `isin` method. Swapping `'John Doe'` for `Query.select('John Doe')` errors with 'no FROM table specified'.

Does PyPika provide a syntax to go about this?

**Comment by twheys** [comment]
Yeah, although maybe we could give a better API for this. There's an internal wrapper class that is not exposed in the top level package, but you can use it:
`import ValueWrapper from pypika.terms`

`ValueWrapper('John Doe').isin(...)`

**Comment by rossjrw** [comment]
Thanks, this works perfectly. The API is fine, imo - just the documentation could use the addition. Not really that much of a concern while the version number starts with 0, though
