### ISSUE TITLE
add Table.select?

### ISSUE THREAD

**Issue by jstrong-tios** [kayak/pypika#264]
Has allowing `Table` to `select`, eliminating the name to re-specify a table name with `from_` been considered? e.g.

```python
from pypika import Table, Query
t = Table('my_table')
t.select(t.x, t.y) == Query.from_('my_table').select(t.x, t.y) # -> True
```

Just an idea. Seems like it would add convenience when using from console/jupyter.

Thanks for your hard work on a great library!

**Comment by twheys** [comment]
Hey, this would be possible, although there are a few additional functions that would have to be considered like `insert` and `update`. Would happily take a PR for this.

**Comment by harshanarayana** [comment]
@twheys Mind if I take a stab at this ?
