### ISSUE TITLE
How to access PostgreSQL JSON fields?

### ISSUE THREAD

**Issue by Dandi91** [kayak/pypika#268]
How do I construct a query like
```sql
SELECT value->'key'->>'subkey' FROM json_table
```
using PyPika?

**Comment by twheys** [comment]
This syntax isn't supported in pypika. This is json notation for postgres, right?

**Comment by Dandi91** [comment]
Correct, it is postgres notation. 

Is there any workaround that I could use to reference such fields in `select` or `where` clauses when writing PyPika queries?

**Comment by mikeengland** [comment]
@Dandi91 This has now been added in the merged PR above.

**Comment by KuzenkovAG** [comment]
example of JSONB query:

```
.where(
    JSON.wrap_json(table.column).get_text_value('key_name').ne('value')
)
```
SQL:
```
WHERE "column"->>'key_name'<>'value'
```
