### ISSUE TITLE
JSONField doesn't respect table kwargs

### ISSUE THREAD

**Issue by jnguyen32** [kayak/pypika#277]
```
json_field = JSONField(val="test_column", table="test_table", alias=None)
print(json_field.get_sql(dialect="postgressql"))
```

Yields:
`"test_column"`

It doesn't seem to follow the same approach `Field`.`get_sql()` takes.

**Comment by twheys** [comment]
Thanks for reporting, will take a look. This feature just got merged so perhaps the test cases didn't cover the full use case.
