### ISSUE TITLE
Double quotes when joining with USING

### ISSUE THREAD

**Issue by liadmat** [kayak/pypika#279]
```python3
q = Query.from_(Table('t1')).join(Table('t2')).using(Field('f')).select(Field('f'))

str(q)
```
Returns:
```sql
SELECT "f" FROM "t1" JOIN "t2" USING (""f"")
```
Similarly,
```python3
q.get_sql(quote_char=None)
```
Returns:
```sql
SELECT f FROM t1 JOIN t2 USING (""f"")
```

I'm trying to get `USING (f)` instead of `USING (""f"")` (obviously, I can remove the double quotes myself).

Am I doing something wrong, or is this a bug?

**Comment by twheys** [comment]
You shouldn't need to use the Field class directly. Try saving the references to the tables and referencing attributes of those tables to produce instances of `Field` :

```
t1 = Table('t1')
t2 = Table('t2')

q = Query.from_(t1).join(t2).using('f').select(t1.f)
```
