### ISSUE TITLE
MySQL TimeDiff function

### ISSUE THREAD

**Issue by kashifali-m398** [kayak/pypika#282]
Is there a function that can translate to code to MySQL TIMEDIFF or TIMESTAMPDIFF function, when we have only time type columns in database not datetime and timestamp.

**Comment by twheys** [comment]
pypika doesn't include an exhaustive list of SQL functions, given that there are so many and depend on which database vendor you're using. 

To create a SQL function wrapper, you can take a look at `DATEDIFF` as an example: https://github.com/kayak/pypika/blob/master/pypika/functions.py#L133

If you'd like to open a PR to add these functions, it would probably make sense to have them included in pypika.
