### ISSUE TITLE
Support for bitwise operators

### ISSUE THREAD

**Issue by AbdulhamidZoubi** [kayak/pypika#284]
Is it possible to add support for bitwise operators in `WHERE` clause.?
for example if I had the `messages` table with the field `status`  of type INT and the bits of the value of this field represent a specific status i.e _delivered_, _seen_, ..etc. Instead of having a separate BOOL field for each status.

supposing that the first bit is for the _delivered_ status and the second one is for the _seen_ status

If i want to retrieve only delivered messages that are not seen yet, the query would be something like:
**```SELECT `status` FROM `messages` WHERE (`status` & 1 = 1) ```**

**Comment by kongzii** [comment]
I have created pull request with this feature: https://github.com/kayak/pypika/pull/288

**Comment by twheys** [comment]
Fixed by #288

**Comment by ekamuktia** [comment]
Anyone tried this one with the latest version? (ver 0.39.0 as of now)
I tried to use bitwiseand for where condition but it returns error because of this line https://github.com/kayak/pypika/blob/master/pypika/terms.py#L807

> AttributeError: 'int' object has no attribute 'nodes_'

I wonder if it's a bug or I use the function incorrectly

**Comment by mikeengland** [comment]
@ekamuktia please can you provide us some example code, and if it fails, raise a new issue? Thanks!

**Comment by ekamuktia** [comment]
Here's the sample code
```
table = Table('table_name')
Query.select(table.star).from_(table).where(table.category.bitwiseand(2))
```

This code is supposed to generate 
> SELECT * FROM table_name WHERE category & 2

But it returns error code as I mentioned before
