### ISSUE TITLE
Dialect for Blazingdb

### ISSUE THREAD

**Issue by argenisleon** [kayak/pypika#291]
Hi,
I would like to contribute to writing a dialect for blazingdb.

I need to output
```"SELECT MIN(`RATING`) FROM main.music"``` or ```"SELECT MIN(RATING) FROM main.music"``` but all the dialect return ```"SELECT MIN('RATING') FROM main.music"```.

It seems easy to extend the dialect but I can not figure out where surrounding chars are attached to the column aggregation. 

Any help?

**Comment by twheys** [comment]
Hi @argenisleon 

You'll want to set the `quote_char` attribute in the dialect. Take a look at MySQL which also uses backticks https://github.com/kayak/pypika/blob/master/pypika/dialects.py#L21

You could also set the `quote_char` to `None`, but having the quote character gets around some issues when special characters are used in the table/column names

**Comment by argenisleon** [comment]
Hi @twheys ,

I just update the main answer. If you look the column names have backticks but the aggregation functions have normal ticks. I use this code with the Mysql dialect

```
from pypika import Query, Table, Field, analytics as an
from pypika.dialects import MySQLQuery as Query

agg = [an.Min('RATING')]

q = Query.from_('main.music').select(*agg)
print(q.get_sql())
```

and I get:
```
SELECT MIN('RATING') FROM `main.music`
```

**Comment by argenisleon** [comment]
Hi @twheys,

Any tip about how I can handle this?

**Comment by twheys** [comment]
You need to use an instance of the Table class in order to set the schema. Passing in the schema and table name as the table name won't work. Try the following:

```
music = Table('music', schema='main')
q = Query.from_(music).select(an.Min(music.RATING))
```
