### ISSUE TITLE
Clickhouse support?

### ISSUE THREAD

**Issue by d-ganchar** [kayak/pypika#293]
Hello. Thanks for repository.

Do you have full _Clickhouse_ support? I didn't found _Clickhouse_ in _database platforms_, but I found [ClickHouseQuery](https://github.com/kayak/pypika/blob/master/pypika/__init__.py#L35)

I checked basic(**SELECT**, **GROUP**, **DISTINCT**) queries and all works fine. But what about specific _clickhouse syntax_? Example:

```
     WHERE match(toString(name), 'twheys') 
       AND hasAny(components, [...])
       AND toString(category) IN (...)
```

Also I saw [issue / 67](https://github.com/kayak/pypika/issues/67) but it was a few years ago. What is the current state of _Clickhouse adaptation_?

Thank you.

**Comment by twheys** [comment]
Hi. I don't recall anything additional being added for Clickhouse. Would recommend checking the related PRs to see what's been added https://github.com/kayak/pypika/pulls?utf8=%E2%9C%93&q=is%3Apr+clickhouse

The example you provided could be pulled off in pypika by adding python wrappers for those sql functions. You can look at how they're implemented in pypika here https://github.com/kayak/pypika/blob/master/pypika/functions.py

**Comment by d-ganchar** [comment]
@twheys сan I contribute?

**Comment by twheys** [comment]
Absolutely. Feel free to open a PR. Let me know if you need any guidance.
