### ISSUE TITLE
Using version 0.33.1 or newer with Python 2.7

### ISSUE THREAD

**Issue by awolfes** [kayak/pypika#297]
Version 0.33.0 imports fine.

Trying to run version 0.33.1 or newer complains about line 341 in queries.py, with regards to how Python 2.7 does not support starred expressions in dictionaries.

```python
kwargs = {
            'dialect': self.base_query.dialect,
            # This initializes the quote char based on the base query, which could be a dialect specific query class
            # This might be overridden if quote_char is set explicitly in kwargs
            'quote_char': self.base_query.quote_char,
            **kwargs,
        }
```

Additionally, any version after 0.28.1 complains about line 108 in queries.py when running the Table function:

```python
TypeError: super() argument 1 must be type, not classobj
```

The section in question:

```python
    def __init__(self, name, schema=None, alias=None):
        super(Table, self).__init__(alias)
        self._table_name = name
        self._schema = self._init_schema(schema)
```

**Comment by teror4uks** [comment]
Hi, I think latest Py2.7 supported version is 0.28.1. https://github.com/kayak/pypika/pull/269

**Comment by awolfes** [comment]
Thanks for the response. I'll be sure to use 0.28.1 going forward with my 2.7 project.
