### ISSUE TITLE
Unclear support for cross-DB joins/queries

### ISSUE THREAD

**Issue by paul-ko** [kayak/pypika#299]
I have use cases where I need to write queries that join across databases, such as

```
select count(*)
from DB1.Schema1.Table1 t1
left join DB2.Schema2.Table2 t2 on t2.col = t1.col
```

I couldn't find anything in the documentation, but digging in the code I noticed that `Schema` objects have a `parent` property, and if I create a schema whose parent is a "schema" with the database name, I can generate the SQL I'd like. For example:

```
t1 = Table('Table1', schema=Schema('Schema1', parent=Schema('DB1')))
t2 = Table('Table2', schema=Schema('Schema2', parent=Schema('DB2')))
Query.from_(t1).join(t2, JoinType.left).on_field('col').select(functions.Count(functions.Star()))
```
I'm curious about a couple of things:

1.  Is this the correct way to do this sort of query? It feels weird to create a `Schema` to represent a database, but I haven't found a better approach.
2.  If the answer to that is yes, would you be interested in a pull request adding documentation on it to your docs somewhere?

Thanks!

**Comment by twheys** [comment]
@paul-ko I'm not sure if this is explicitly supported right now but would be a relatively easy add. Interesting how you ended up solving it, but no that would be ideal. Will push a quick change to address this.

**Comment by paul-ko** [comment]
Thanks - I'll be looking forward to that!  I'll keep an eye on this issue in case there's anything I can help with.
