### ISSUE TITLE
Add escaping for SQL characters

### ISSUE THREAD

**Issue by twheys** [kayak/pypika#3]
Any input into pypika should escape invalid characters.  This includes table names, field names, and values.

**Comment by spinningarrow** [comment]
Is there any workaround for this in the current version?

**Comment by twheys** [comment]
Not currently, except to escape the characters on the result query string itself

**Comment by spinningarrow** [comment]
@twheys thanks for the suggestion! I think it would definitely help to have this supported. If it's fairly straightforward, I can also take a stab at it and make a PR if you'd like.

**Comment by twheys** [comment]
Yeah if you have time to do it, your contribution would be greatly appreciated 👍  There are some comments in different places in the code with TODOs where it the escaping should be applied

**Comment by spinningarrow** [comment]
I can't make any promises at the moment; I'm no longer working on the project that requires this 🙈

**Comment by twheys** [comment]
No worries

**Comment by reutsharabani** [comment]
@twheys How would you implement this? One way is to make sure all methods that receive inputs are validating it (escaping) - very prone to error on extension (someone may forget...)

The other method is to escape everything on `get_sql` (or the string creation).

Do you have a preferred way (possibly something else)?

**Comment by twheys** [comment]
There's a couple of places where it needs to be done. Basically, anywhere a parameter is taken that ends up rendered in the query. For example, table names and schemas, `ValueWrapper` values, etc. The escape function probably only needs to escape the quote characters, as long as what is being escaped is inside a string or something. Might prove a bit more complicated than that, though.

**Comment by reutsharabani** [comment]
@twheys I may be able to spend time on it this weekend or the next one. Do you have any guidelines on how to do it?

Honestly, I think this is crucial for this library to be usable for any interaction with input from the real world.

**Comment by twheys** [comment]
@reutsharabani sorry I didn't reply before the weekend. I don't have a particular solution in mind. I think the problem might be more complicated that it first appears, though, perhaps not. My thoughts were to make an escape function that replaced any special characters such as `;` in the arguments that need it.  I think the escaping should only need to be done on string arguments, not the whole get_sql output, otherwise you'll be escaping characters that the pypika internals are writing.

**Comment by reutsharabani** [comment]
@twheys no problem.

I think a custom escape function is meaningless. The functions are usually exposed by the drivers so just take it as an argument. I strongly suggest it to be at a single point that everything passes through, Otherwise it is hard to maintain (scattered around the code).

About escaping pypika internals - my idea was applying it at a single point before doing something with the values. If the values are mutated before that point it obviously won't work.

I will probably take a look at the weekend to get familiar with the code and see if I come up with something.

**Comment by grigi** [comment]
I think that there is two different ways to harden the query:
1) Escaping the identifiers (e.g. table/column/alias names)
2) Escaping the data

I feel we should definitely do 1, and it would be different for each dialect. e.g. MySQL uses \` (backtick), etc... We can get away with this as identifiers have a limited character set. We also must do it as there is no other way.

I feel we should not attempt 2, and find a way to treat data as binary instead (as in parametrized queries) as that is the only recommended way in most systems to access a database, as the data goes in a separate data structure.

**Comment by twheys** [comment]
Gonna close this since parametrized queries perform this role.
