### ISSUE TITLE
AND / OR operators?

### ISSUE THREAD

**Issue by d-ganchar** [kayak/pypika#302]
I looked at the [filter documentation](https://pypika.readthedocs.io/en/latest/2_tutorial.html#filtering). 

- I have _list_ of teams(`teams = ['team1', 'team2']`)
- I have _list_ of statuses(`statuses = ['open', 'in progress']`)

How can I make the following query?

```
WHERE created = '2019-01-01' 
     AND (  team = 'team1' OR team = 'team2' )
     AND ( status = 'open' OR status = 'in progress' )
```

Do you have any expressions(_or_()_ / _and_()_ / _where_or()_ etc.) (for example like in [sqlalchemy](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.or_) )?

**Comment by twheys** [comment]
I think a reduce pattern would be a good approach here. Something like this:
```
import functools

def reduce_or(criterions): 
    return list(functools.reduce(lambda a, b: a | b, criterions))
```

Then you can pass a list of the criterion objects you get from pypika expressions, such as

```
table = ...
query = ...
query = query.where(table.created == '2019-01-01') \
    .where(reduce_or([table.team == team for team in teams])) \
    .where(reduce_or([table.status == status for status in statuses]))
```

*Pypika doesn't itself include a helper function for this.*

Alternatively, you can use the `isin` query builder function and create a similar query with the same effect:

```
table = ...
query = ...
query = query.where(table.created == '2019-01-01') \
    .where(table.team.isin(teams)) \
    .where(table.status.isin(statuses)
```
which will yield something like 
```
WHERE created = '2019-01-01' 
     AND team in ('team1', 'team2')
     AND status in ('open', 'in progress')
```

**Comment by d-ganchar** [comment]
@twheys thank you. I was thinking about `isin`, but as far as I remember (I may be wrong), in some cases _multicolumn indexes_ with `IN` doesn't work. I was interested in example with `reduce_or`.
