### ISSUE TITLE
Semantically different queries generated in some cases depending on usage of comparison functions vs. operators in complex criteria

### ISSUE THREAD

**Issue by paul-ko** [kayak/pypika#304]
I ran into an issue in which the where clause in one of my queries didn't include parentheses to group an ORed criterion that then ANDed with another criterion.  In other words, I wanted `(A | B) & C`, but I got `A | B & C`

This resulted in a query that returned unexpected results, because the lack of parentheses meant it was interpreted as meaning `A | (B & C)` instead of the desired `(A | B) & C`, due to AND having higher precedence than OR.

The lack of parentheses seemed inconsistent with my experience with pypika so far, and when I investigated further I found that the generated SQL actually varies depending on whether the second criterion in the ORed complex criterion uses an operator (`<`, `==`) or a function (`lt()`, `eq()`).

Here is some ugly demo code:

```
from datetime import datetime

from pypika import Query, Table
from pypika.functions import DateDiff
from pypika.enums import DatePart


def generate_queries():
    def print_queries():
        print('with == operator:', q_with_op)
        print('with eq function:', q_with_func)

    tbl = Table('query_tbl', schema='scm')
    base_q = Query.select(tbl.a).from_(tbl)
    date_diff = DateDiff(DatePart.minute, tbl.a, datetime.now())

    q_with_op = base_q.where(tbl.a.isnull() | date_diff == 0)
    q_with_func = base_q.where(tbl.a.isnull() | date_diff.eq(0))
    print_queries()

    q_with_op = q_with_op.where(tbl.d.isnull())
    q_with_func = q_with_func.where(tbl.d.isnull())
    print_queries()


generate_queries()
```

Here is the output:

```
with == operator: SELECT "a" FROM "scm"."query_tbl" WHERE "a" IS NULL OR DATEDIFF(MINUTE,"a",'2019-08-21T09:54:27.399709')=0
with eq function: SELECT "a" FROM "scm"."query_tbl" WHERE "a" IS NULL OR DATEDIFF(MINUTE,"a",'2019-08-21T09:54:27.399709')=0
with == operator: SELECT "a" FROM "scm"."query_tbl" WHERE "a" IS NULL OR DATEDIFF(MINUTE,"a",'2019-08-21T09:54:27.399709')=0 AND "d" IS NULL
with eq function: SELECT "a" FROM "scm"."query_tbl" WHERE ("a" IS NULL OR DATEDIFF(MINUTE,"a",'2019-08-21T09:54:27.399709')=0) AND "d" IS NULL
```

You can see that when I only add the two ORed criteria, the generated SQL is identical regardless of whether I use `== 0` or `.eq(0)`.  However, after I call `where()` again to add a new criterion, the initial complex criterion is enclosed in parentheses if it ended with a `.eq()` call, but not if it ended with a usage of `==`.

I've reproed this with `.lt()` vs `<` as well.

**Comment by twheys** [comment]
this is the problem: `tbl.a.isnull() | date_diff == 0` 

Since the `|` and `&` are viewed as bitwise operators in python, they take precedence in the order of operations, so it's going to evaluate `tbl.a.isnull() | date_diff` first, then the result of that `... == 0` afterwards. This is a python language spec, so there isn't much that can be done about it.

To get around this, you can wrap your python expressions in parenthesis when using the bitwise operators `tbl.a.isnull() | (date_diff == 0)`

**Comment by paul-ko** [comment]
Ah, makes sense. I appreciate the explanation.
