### ISSUE TITLE
ALTER / TRUNCATE?

### ISSUE THREAD

**Issue by d-ganchar** [kayak/pypika#319]
Hello.

How can I add custom implementation of **ALTER TABLE**.
_Clickhouse_ has [specific syntax](https://clickhouse.yandex/docs/en/query_language/alter/#alter-mutations). Can you provide a small example how can I do it? Just your vision and wishes.

Also I didn't found _TRUNCATE_ possibility.

**Comment by Cruuncher** [comment]
As alter table is so different for every database system, I'm not sure this is a good tool to use for writing it, as stated in the goals of this library. It's also not typically something that you need to build, they're pretty static.

Similarly you don't really need a library to write truncate table for you. But that one is surely easy to add
