### ISSUE TITLE
Query error in Documentaion on PyPi

### ISSUE THREAD

**Issue by shadab-entrepreneur** [kayak/pypika#333]
While going through the documentation and installation page of PyPika on PyPi, for a given sample code, the query which gets generated is shown wrong.
For reference find the below pic:

<img width="597" alt="doc_error" src="https://user-images.githubusercontent.com/10863620/67003965-d6579680-f0fc-11e9-8dba-16eeac9f0c39.png">

Link: [PyPika PyPi](https://pypi.org/project/PyPika/) 

The actual query should be:
SELECT "id",SUM("revenue") FROM "customers" WHERE "age">=18 GROUP BY "id"

Can someone get it fixed or let me know how to get fixed?

**Comment by twheys** [comment]
yes, you're right. definitely looks like a bug. Will take a look.

**Comment by shadab-entrepreneur** [comment]
Thanks @twheys :)
