### ISSUE TITLE
Can I build a query like "select '1' as age, `name`  from  test_table;"?

### ISSUE THREAD

**Issue by songkang1993** [kayak/pypika#339]
like this:
from sqlalchemy import literal
select([literal('1').label('test'), User.c.username])

**Comment by twheys** [comment]
Yeah, you can use the `ValueWrapper` class for this. It's usually applied automatically to raw python values when they're passed directly into the select function, but in your case you could use it directly:

Something like 
```
from pypika import Table, Query, ValueWrapper

c = Table("c", schema="User")
Query.from_(c).select(ValueWrapper('1').as_('test'), c.username)
--> SELECT 1 as "test", username from User.c
```
