### ISSUE TITLE
Cast function surrounds term with single quotes instead of double quotes

### ISSUE THREAD

**Issue by axmccx** [kayak/pypika#350]
The postgres table I'm working with has periods in the column names. I cannot change this. I need to cast some columns as TEXT, but the cast function is wrapping the term/column name in single quotes instead of double quotes. 

Postgres appears to be treating this as a string, instead of a column name. In the example below, product.type should be wrapped with double quotes. Is there a way to do this?

```
customers = Table("customers", schema="results_a")
q = Query.from_(customers).select(
    "id", 
    "customers.fname", 
    "customers.lname", 
    fn.Cast("product.type", "text")
)

SELECT "id","customers.fname","customers.lname",CAST('product.type' AS TEXT) FROM "results_a"."customers"

**Comment by twheys** [comment]
@axmccx if you pass in a string argument to cast, it'll be handled as such in the query `fn.Cast("product.type", "text")`

Instead, get field reference using the instance of table like `fn.Cast(customers['product.type'], "text")` and it'll get conveyed in the query correctly.

**Comment by twheys** [comment]
also worth mentioning: the select function has special cases for it's arguments which convert string args into fields under the hood. This is syntactic sugar but not handled the same way for all functions and classes in pypika because in most other places, strings are valid arguments in the sql

**Comment by axmccx** [comment]
This is great! Thanks so much for you quick response!
