### ISSUE TITLE
Using "alias" as a field name

### ISSUE THREAD

**Issue by RafRaf** [kayak/pypika#351]
Hey, community. We've found some strange behavior of `Query`'s select. It seems like `alias` is a reserved word. We can't use it as a field name.

Example:
```python
my_table = Table('my_table')
q = Query.from_(my_table).select(my_table.id, my_table.name, my_table.alias)
```
Result:
```
SELECT "id","name",NULL FROM "my_table"
```
But let's replace `alias` to `alias2`:
```
my_table = Table('my_table')
q = Query.from_(my_table).select(my_table.id, my_table.name, my_table.alias2)
```
And now it works as expected:
```
SELECT "id","name","alias2" FROM "my_table"
```
😔
PS: pypika==0.35.15

**Comment by twheys** [comment]
Yeah alias is a reserved field name. There is another syntax for creating fields that will work in this case:
`my_table['alias']`

Alternatively, you could create the field directly:
`Field('alias', table=my_Table)`
