### ISSUE TITLE
pypika release on PyPI missing join convenience methods

### ISSUE THREAD

**Issue by sighduck1** [kayak/pypika#353]
I installed `pypika` with `pip install pypika`, which installs version `PyPika==0.35.15`. I tried to use the `left_join` method mentioned in the README with the example query in the tests:

```python
>>> from pypika import JoinType, Query, Tables
>>> table0, table1, hij = Tables('abc', 'efg', 'hij')
>>> Query.from_(table0).join(table1, how=JoinType.left).on(table0.foo == table1.bar).select("*")
SELECT * FROM "abc" LEFT JOIN "efg" ON "abc"."foo"="efg"."bar"

>>> Query.from_(table0).left_join(table1).on(table0.foo == table1.bar).select("*")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Field' object is not callable

```

The latest version of `pypika` on PyPI (https://pypi.org/project/PyPika/0.35.15/) does not contain the join convenience methods. Would it be possible to update the version of `pypika` on PyPI?

Thank you for creating the library!

**Comment by twheys** [comment]
Those functions were added in `0.35.16`... maybe I forgot to publish it.. let me check

**Comment by twheys** [comment]
ok yeah looks like there was a compile error in the README.rst that prevented the publish. Fixed now and published.
