### ISSUE TITLE
How to do Sample in pl/sql

### ISSUE THREAD

**Issue by HYChou0515** [kayak/pypika#354]
PL/SQL support [Sample](https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10002.htm#i2105143) to select a random portion of a table. 

To select 10% from `my_table`

```
SELECT * FROM my_table SAMPLE(10);
```

To combine with `JOIN`

```
SELECT A.x, B.y
FROM A SAMPLE(10) JOIN B SAMPLE(5) ON A.z=B.z
```

Sometimes `SEED`  may be needed after `SAMPLE` to assign the random seed for the sample function.

```
SELECT A.x, B.y
FROM A SAMPLE(10) SEED(1) JOIN B SAMPLE(5) SEED(2) ON A.z=B.z
```

In Pypika, how to do the similar task, i.e., how to insert some custom sql clauses after the table clause.

**Comment by twheys** [comment]
Please see the docs on the section about creating custom functions https://pypika.readthedocs.io/en/latest/2_tutorial.html#custom-functions

**Comment by HYChou0515** [comment]
Hi @twheys, the [doc ](https://pypika.readthedocs.io/en/latest/2_tutorial.html#custom-functions) of custom functions handles syntax like `SAMPLE(A, B)` but not `MY_TABLE SAMPLE(0.1)`. Is such syntax possible? I couldn't find a related doc.
