### ISSUE TITLE
MSSQLQuery "top"

### ISSUE THREAD

**Issue by sivabudh** [kayak/pypika#358]
With a Microsoft SQL Server database, we cannot use `.limit(N)` but we need to use 

```
SELECT TOP N
```
Ref: https://www.w3schools.com/sql/sql_top.asp

Does Pypika support `TOP`? I've already tried:

```
from pypika import MSSQLQuery
qry = MSSQLQuery.from_(table).select(...).limit(100)
```
But when I execute the query, I get:

```
Execution failed on sql 'SELECT <field names> FROM "<table name>" LIMIT 100': <class 'pyodbc.Error'> returned a result with an error set
```

**Comment by sabrikaragonen** [comment]
If you try `MSSQLQuery.from_(table).select(...).top(100)`, it will work.
However I agree that pypika should render limit as top.

**Comment by twheys** [comment]
Pypika does not try to convert it's syntax into different dialects. You can create an instance `PseudoColumn` and select it like

```
TopN = PseudoColumn('TOP N')

Query.select(TopN)
```
