### ISSUE TITLE
additional Join functionality 

### ISSUE THREAD

**Issue by cjstudioz** [kayak/pypika#36]
- It would be a nice convenience function just to specify a string or list of strs if the column(s) to join on are the same in both tables. e.g. from_(t1).join(t2).on('c1')

- it's not clear how I can construct a join USING clause "... from t1 join t2 USING (c1, c2)"

i'm happy to contribute if this is not yet available but you think would be helpful

I'm sorry the docs don't show a preferred method of getting in touch. please suggest most appropriate communication channel. You can look me up as "CJ Lee" from London on linkedin

P.S. love this package thanks for this

**Comment by twheys** [comment]
Hi CJ, thanks for the feedback. Nice to hear that you like pypika.  Yeah, we can add support for joining with string keys and add a using function as well.  Will submit a pull request soon.

**Comment by cjstudioz** [comment]
Thanks, is there a way to communicate with you? you can get me on "cjstudios - gmail" (I'll leave you to decipher that)

**Comment by twheys** [comment]
In the PR I only added support for `USING` since I assume you can accomplish what you'd like to do with just that and left `ON` joins as they are.  Let me know if this works for you.

**Comment by cjstudioz** [comment]
'using' has a slightly different side effect in many dbs of combining the
join col into one, e.g. I cannot reference t1.joincol separately from
t2.joincol

hence there is still significant value in providing an "on" operator (
perhaps call it onKey() ) which takes a list of strings.

**Comment by twheys** [comment]
So the behavior of `onKey(fields)` should be to join on the equality criteria of each of the columns in both the base table and the join table?  This wouldn't cover joining a table through another joined table, although using the existing `on(criterion)` syntax covers that.

**Comment by cjstudioz** [comment]
If I understood what you're saying: one could do: _t1.col1 join t2.col1_  with onKey() but **cannot** do _t1.col1 join t2.col2_

If I understood you correctly, then yes I agree the onKey() 'limitation' is expected since it is only meant as a convenience function

**Comment by twheys** [comment]
How should this behave if there are multiple from tables?  Should just use the first table in the from clause?

For example:
```
SELECT name, price, photo
FROM drinks, drinks_photos
WHERE drinks.id = drinks_id 
GROUP BY drinks_id
```

**Comment by twheys** [comment]
btw I tried to ping you on google hangouts

**Comment by twheys** [comment]
https://github.com/kayak/pypika/pull/39

**Comment by twheys** [comment]
@cjstudioz I pushed v0.2.5 to pypi containing all the fixes you requested.

I named the join on function `on_field(*fields)` which takes a variable number of string arguments representing field names
