### ISSUE TITLE
.orderby($list) does not accept list of strings as Input

### ISSUE THREAD

**Issue by Kulu-M** [kayak/pypika#360]
query = query.orderby(["ID", "SID"])

will result in 

	ORDER BY ['ID','SID']

Which is invalid SQL syntax.

**Comment by twheys** [comment]
Some flavors of SQL support arrays, therefore pypika converts a python list into an array with square bracket syntax, aligning with the python syntax. If you want to use parantheses, use a python tuple: `query = query.orderby(("ID", "SID"))`. I think the `orderby` function also supports varargs as well, and will convert it to a tuple, so if you pass in just `query = query.orderby("ID", "SID")` you should get the result you're looking for as well.
