### ISSUE TITLE
Is there a way to dynamically create WHERE clauses?

### ISSUE THREAD

**Issue by Kulu-M** [kayak/pypika#365]
Using WHERE with OR, in the example it says the following:

```
customers = Table('customers')
q = Query.from_(customers).select(
    customers.id, customers.fname, customers.lname, customers.phone
).where(
    (customers.age >= 18) | (customers.lname == 'Mustermann')
)
```

If I have some kind of collection with desired filters, is there any way to create this dynamically? For example:
```
filters = [
		{'field': 'customers.age', 'operator': '>=', 'value': '18'},
		{'field': 'customers.lname', 'operator': '==', 'value': 'Mustermann'}
]
```

Something like

```
query = query.where([for f in filters])
```
If not, what would be the best way to react on unknown filter amounts and fields/values/operators? 

Thanks

**Comment by twheys** [comment]
Hey, yeah i don't think it's documented any where but there are `all` and `any` static functions on `Criterion`

```
from pypika import Criterion
Criterion.any([
  customers.age >= 18,
  customers.lname == 'Mustermann'
])
```

**Comment by Mohit-97** [comment]
> Hey, yeah i don't think it's documented anywhere but there are `all` and `any` static functions on `Criterion`
> 
> ```
> from pypika import Criterion
> Criterion.any([
>   customers.age >= 18,
>   customers.lname == 'Mustermann'
> ])
> ```

@twheys I think @Kulu-M wanted to generate dynamic filters from dict or any list of filters not just hard-coding the filter like table.filter_col=value, etc.

Is there any solution in regards to this

**Comment by reidswanson** [comment]
> @twheys I think @Kulu-M wanted to generate dynamic filters from dict or any list of filters not just hard-coding the filter like table.filter_col=value, etc.
> 
> Is there any solution in regards to this

I'm very new to PyPika, but wanted to know the same thing, so for anyone else wondering about this, I believe you can use the `field` attribute of the `Table` class.

```
import pypika

table = pypika.Table("atable")
column_name_1 = "colname_1"
column_name_2 = "colname_2"

Criterion.any([
    table.field(column_name_1) == "some_value",
    table.field(column_name_2 > 5
])
```

**Comment by mattiagiupponi** [comment]
> @twheys I think @Kulu-M wanted to generate dynamic filters from dict or any list of filters not just hard-coding the filter like table.filter_col=value, etc.
> Is there any solution in regards to this

Hi,
I know is an old topic, but maybe someone is still looking for this.

Thanks to the `Criterion` is possible to generate complex dynamically starting from any iterable. Follow a small example of how to implement it and how is going to be integrated into the pypika query.

Let's assume that we have the following iterable:

```python
my_iterable = [
    {"label": "my_field", "value": 10},
    {"label": "my_field", "value": 100}
]
```


```python
# Table and query definition
from pypika import Query, Table
from pypika import Criterion
t = Table('mytable')
query = Query.from_(t).select(t.my_field)
```

Now let's dynamically set the conditions:

```python
conds = []
for element in my_iterable:
    condition_field = getattr(t, element['label'])
    conds.append(condition_field > element['value']) #<--- I strongly suggest to make this as a function and return the condition needed 

print(conds)
conds
[<pypika.terms.BasicCriterion object at 0x7f9c40d53fd0>, <pypika.terms.BasicCriterion object at 0x7f9c40d53e80>]

# any for an OR
condition = Criterion.any([x for x in conds])
# all for an AND
condition = Criterion.all([x for x in conds])

query.where(condition)
print(query)

SELECT "my_field" FROM "mytable" WHERE "my_field">10 OR "my_field">100
```
