### ISSUE TITLE
Escape columns according if using database specific Query classes

### ISSUE THREAD

**Issue by khalyomede** [kayak/pypika#367]
**Description**

I did not saw in the documentation how to escape the columns, and I expected this library to do it in a way or another. In my case I expected it to automatically escape the columns.

**Reproduce**

Save the following code in a file `test.py`

```python
from pypika import MySQLQuery, MSSQLQuery, PostgreSQLQuery, Table

table = Table("user")
mysql_query = MySQLQuery.from_(table).select("id", "external_id", "name", "from", "user")
mssql_query = MSSQLQuery.from_(table).select("id", "external_id", "name", "from", "user")
postgresql_query = PostgreSQLQuery.from_(table).select("id", "external_id", "name", "from", "user")
mysql_query_string = mysql_query.get_sql()
mssql_query_string = mssql_query.get_sql()
postgresql_query_string = postgresql_query.get_sql()

print("**** MySQL QUERY ****")
print(mysql_query_string)
print("**** MSSQL QUERY *****")
print(mssql_query_string)
print("**** PostgreSQL QUERY *****")
print(postgresql_query_string)
```

See the output in console.

```bash
python test.py
```

```
**** MySQL QUERY ****
SELECT id,external_id,name,from,user FROM user
**** MSSQL QUERY *****
SELECT id,external_id,name,from,user FROM user
**** PostgreSQL QUERY *****
SELECT id,external_id,name,from,user FROM user
```

**Expected result**

To see in console the escaped columns.

```
**** MySQL QUERY ****
SELECT `id`,`external_id`,`name`,`from`,`user` FROM user
**** MSSQL QUERY *****
SELECT [id],[external_id],[name],[from],[user] FROM user
**** PostgreSQL QUERY *****
SELECT "id","external_id","name","from","user" FROM user
```

**Notes**

1. Maybe the `pypika.Field` should be updated to produce the same output in case we are calling this class only with a column like `Field("user")`?
2. Maybe this could be opt-in in a way or another, meaning if you decide to resolve this issue, 
    - to make the library to automatically escape the columns, with an option in a defined location (on the class level?) to let the developer to disable this behavior (like `.select("id", "user", escape=False)`)
    - to make the library not to do anything without the developer to specify wether he want to escape columns or not (like `.select("id", "user", escape=True)`)
3. This goes beyond the scope of this issue (for the moment?), but maybe extend this escape feature to table names also?

**Comment by twheys** [comment]
By escape do you mean wrapping column references with quotes? If I run your sample code I get the following result:
```
**** MySQL QUERY ****
SELECT `id`,`external_id`,`name`,`from`,`user` FROM `user`
**** MSSQL QUERY *****
SELECT "id","external_id","name","from","user" FROM "user"
**** PostgreSQL QUERY *****
SELECT "id","external_id","name","from","user" FROM "user"
```

I'm not terribly familiar with mssql, however, I believe there are some people who use pypika with mssql, this dialect specific class was contributed by one of them, and they didn't set the quote character. Maybe the double quote works as well as brackets?

What version of pypika are you using?

**Comment by khalyomede** [comment]
After running `pip list` I got

```
...
PyPika        0.9.4
...
```

**Comment by twheys** [comment]
you've got a really old version. Can you please upgrade to the latest?

**Comment by khalyomede** [comment]
It worked, I upgraded to `0.38.*` and it correctly returned the expected output. Got baited by the published tags (did not browsed the last version on PyPI).

**Comment by twheys** [comment]
good to hear :) thanks for reporting anyway. If you run into any other issues, please don't hesitate to open another ticket.
