### ISSUE TITLE
expose "with_quotes" param on Query and Table objects

### ISSUE THREAD

**Issue by cjstudioz** [kayak/pypika#37]
would like this to propagate the "with_quotes" down to all the get_sql() functions.

Reason:
I would like a way to turn off quoting. My use cases are very simple and would like to keep the SQL I generate easy to read. this also avoids case sensitivity errors.

**Comment by twheys** [comment]
Right now we force quotes to always be on because it prevents any issues with field names, although I don't see any reason why it shouldn't be configurable via parameters.

**Comment by twheys** [comment]
@cjstudioz I pushed v0.2.5 to pypi containing all the fixes you requested.  You can now call `query.get_sql(quote_char=None)` to get a query formatted without quotes.

**Comment by jannikmi** [comment]
Has this feature been documented in the documentation?
