### ISSUE TITLE
Support list, tuple or set with Querybuilder columns method

### ISSUE THREAD

**Issue by lntuition** [kayak/pypika#372]
Hello :) I found that Querybuilder columns only get `*args`
I think allowing iterable params can be useful to user. 

AS-IS
``` python
Query.into("table").columns("name1", "name2", "name3")
```

TO-BE
```
Query.into("table").columns(["name1", "name2", "name3"])
```

How about support this feature?
If you agree, i will make patch with some testcases.
Plz check this and have a nice day :+1:

**Comment by twheys** [comment]
Thanks for the input. I do agree, in fact this has been in the back of my mind for a while now to refactor. If you want to open a PR with this change I'd be happy to review it.

**Comment by lntuition** [comment]
@twheys thank you for comment :) I make PR with simple solution. Please review about this solution :+1:
