### ISSUE TITLE
Boolean comparison filter

### ISSUE THREAD

**Issue by heronfonsaca** [kayak/pypika#375]
I have noticed that there is no mention to bool comparisons in the docs.
I was trying to achieve a filter close to:
```sql
SELECT .. FROM .. WHERE column_name IS TRUE
```
And thought that this could be achieved by PyPika using something like:
```python
q.where(table.column is True)
```

I managed to fake it in order to work on PostgreSQL with:
```python
q.where(table.column == Cast(1, 'BOOLEAN'))
``` 
Is this a possible feature to be worked on?

**Comment by twheys** [comment]
The syntax for is expressions is the `.is_(...)` function on fields.

```
q.where(table.column.is_(True))
```

There's also `pypika.Not` which can be used to negate boolean expressions.
