### ISSUE TITLE
created sql could not be executed on mysql

### ISSUE THREAD

**Issue by jufei** [kayak/pypika#380]
hi:

from pypika import Query, Table, Field
test = Table('tbltest')
q = Query.into(test).columns('name').insert('abc')
>>> q.get_sql()
'INSERT INTO "tbltest" ("name") VALUES (\'abc\')'

mysql> INSERT INTO "tbltest" ("name") VALUES (\'abc\');
ERROR: 
Unknown command '\''.
ERROR: 
Unknown command '\''.
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"tbltest" ("name") VALUES (\'abc\')' at line 1

mysql> INSERT INTO "tbltest" ("name") VALUES ('abc');
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"tbltest" ("name") VALUES ('abc')' at line 1
mysql> 

my own sql statement:
mysql> insert into tbltest(name) values('abc');
Query OK, 1 row affected (0.00 sec)

Thanks.

**Comment by jimorie** [comment]
Try using the MySQL dialect of Query instead: MySQLQuery.

```
>>> from pypika import MySQLQuery as Query, Table, Field
>>> test = Table('tbltest')
>>> Query.into(test).columns('name').insert('abc')
INSERT INTO `tbltest` (`name`) VALUES ('abc')
```
