### ISSUE TITLE
MSSQL DATEDIFF wraps datepart in single quotes

### ISSUE THREAD

**Issue by jaymegordo** [kayak/pypika#384]
The DateDiff function always returns the raw sql in the format:
`DATEDIFF('d','2019-01-01','2019-12-01')`

where MSSQL (T SQL at least) only accepts:
`DATEDIFF(d,'2019-01-01','2019-12-01')`

without the single quotes on the datepart.

Is there any way to allow pypika to return either a non-quoted datepart, or even a double-quoted one?

**Comment by DGalt** [comment]
I ran in to this issue today, and after some digging figured out a way to at least get this to behave in such a way that it produces valid SQL for MSSQL

If you specify the interval as a `Field` then you'll get more control over the quoting around it. This may not be intended behavior, I have no idea, but it works. 

Simple example: 

```
from pypika import Query, Table, Field
from pypika.functions import DateDiff

t = Table('test')
Query.from_(t).select(DateDiff(Field('day'), t.Date1, t.Date2)
```

produces:

`SELECT DATEDIFF("day","Date1","Date2") FROM "test"`

or using `get_sql(quote_char=None)`:

`'SELECT DATEDIFF(day,Date1,Date2) FROM test'`

**Comment by twheys** [comment]
MSSQL is special in this case, since the other DBs like the date part parameter wrapped in quotes. Instead of using a `Field` and `get_sql(quote_char=None)` (which would definitely work unless you end up needing quote characters, you can alternatively use `PseudoColumn` object, which won't ever get wrapped by quote characters, like:

```
from pypika import Query, Table, Field, PseudoColumn
from pypika.functions import DateDiff
from pypika.terms import PseudoColumn

t = Table('test')
Query.from_(t).select(DateDiff(PseudoColumn('day'), t.Date1, t.Date2)
```
