### ISSUE TITLE
Pypika Criterion issue 

### ISSUE THREAD

**Issue by nikkitha92** [kayak/pypika#395]
Hello, 

When i try to add dynamic variables to criterion in the following way : 

filters = {'brand_name':'budweiser','Age_group':'30-35','gender':'Male'}

criterion = Criterion.any(customers.key == value for key,value in filters.items())

customers = Table('final_table_vr')
q = Query.from_(customers).select(
    customers.user_id,customers.name,customers.age
).where(criterion)

Output : 

SELECT "user_id","name","age" FROM "final_table_vr" WHERE "key"='budweiser' OR "key"='30-35' OR "key"='Male'

However i should get the actual key values. Could someone please help

**Comment by lntuition** [comment]
It is non pypika related issue... did you ever use `customers[key]` instead of `customers.key` ? Before reporting the issue, you need to check your python code first.
