### ISSUE TITLE
Release engineering: Use git tags

### ISSUE THREAD

**Issue by PromyLOPh** [kayak/pypika#416]
Hi, I’m maintaining the guix package for pypika and having tagged releases in git would help. We generally run the test suite of packages (if available and feasible). pypika’s PyPi source package lacks the folder pypika/tests, so I’m falling back to specific git commits right now.

Thank you!

**Comment by twheys** [comment]
we've been using `bumpversion` since 0.35.2 which tags the git branch, since then. all releases should have been tagged.

**Comment by PromyLOPh** [comment]
I don’t see any tags or branches here on github. Am I missing something?

**Comment by twheys** [comment]
appears i haven't been pushing them ... they are there now. could you have a look again, please?

**Comment by PromyLOPh** [comment]
Excellent, thank you!
