### ISSUE TITLE
Field' object has no attribute 'is_'

### ISSUE THREAD

**Issue by cheunhong** [kayak/pypika#437]
`.is_` method does not seems to be supported now

**Comment by gl3nn** [comment]
Please give more detailed information and an example that gives you this error.

**Comment by cheunhong** [comment]
```
from pypika import Table, Query

customers = Table('customers')

sql = (
    Query
    .from_(customers)
    .select('*')
    .where(customers.first_time.is_(True))
)

print(sql.get_sql()
```
received this error after running 
`'Field' object has no attribute 'is_'`

**Comment by lntuition** [comment]
@cheunhong What's your real purpose? if you want to compare value, you can use `==`, or if you want to use `IS NULL` syntax you can use `isnull()`

**Comment by cheunhong** [comment]
@lntuition not much really, was just thinking to flag to you guys on this.  as i saw another closed issue which showcase the usage of this.
