### ISSUE TITLE
Postgre allows for intelligent updates on conflicts.

### ISSUE THREAD

**Issue by seandstewart** [kayak/pypika#443]
As [documented](https://www.postgresql.org/docs/9.5/sql-insert.html), PostgreSQL allows for users to intelligently reference the conflicting rows in `ON CONFLICT` statements using the `EXCLUDED` global:

```SQL
INSERT INTO distributors (did, dname)
    VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc')
    ON CONFLICT (did) DO UPDATE SET dname = EXCLUDED.dname;
```

However, the current `.on_conflict().do_update()` syntax requires that an explicit value be given for every field. Ideally, the `value` parameter would be optional and if not provided, the query builder would default to this syntax for the provided field. There's not currently a way to bake this myself, as passing in `q.do_update(field, f"\"EXCLUDED.{field.name}\"")` is automatically escaped:

```python
import pypika

table = pypika.Table("foo")

q = pypika.PostgeSQLQuery.into(table)

stmt = q.insert(1, 2).on_conflict("bar").do_update("blah", "\"EXCLUDED.blah\"")
print(stmt)
#> INSERT INTO "foo" VALUES (1,2) ON CONFLICT ("bar") DO UPDATE SET "blah"='"EXCLUDED.blah"'
```

EDIT:

Upon further poking, I'm able to generate the correct sql by creating a pseudo-table for this case:

```python

exc = pypika.Table("EXCLUDED")
stmt = q.insert(1, 2).on_conflict("bar").do_update("blah", exc.blah)
print(stmt)
#> INSERT INTO "foo" VALUES (1,2) ON CONFLICT ("bar") DO UPDATE SET "blah"="EXCLUDED"."blah"
```

This will do for now, but I think it would be useful to provide a more transparent way to make this happen, or at the very least document this case, so I'll leave the ticket open for triage.

**Comment by lntuition** [comment]
I think it is really good point and i think without `value` with `do_update` should be worked with EXCLUDED keyword. I'll make PR for this feature :smile:

**Comment by seandstewart** [comment]
@lntuition FYI, looks like you cannot double-quote `EXCLUDED` since it’s not an actual schema. https://github.com/MagicStack/asyncpg/issues/591

**Comment by lntuition** [comment]
@seandstewart Thanks for your information. I'll check and fix PR soon :smile:
