### ISSUE TITLE
Snowflake ALIAS Quote chars on joins

### ISSUE THREAD

**Issue by Shawe82** [kayak/pypika#446]
@mikeengland Thanks for letting me know that you have reverted the original fix https://github.com/kayak/pypika/pull/439. I now digged a bit deeper into the quote char issues, and it is not in general and issues but only on table joins. To see what I mean, here the following simple example

```python
from pypika import Table
from pypika.dialects import SnowflakeQuery
t1 = Table("data1")
t2 = Table("data2")
q1 = SnowflakeQuery.from_(t1).select(t1.b).as_("q1")
q2 = SnowflakeQuery.from_(t2).select(t2.b).as_("q2")
q3=SnowflakeQuery.from_(q1).join(q2).on(q1.b==q2.b).select("*")
```
would result in
`SELECT * FROM (SELECT b FROM data1) "q1" JOIN (SELECT b FROM data2) "q2" ON q1.b=q2.b ` which doesn't work. What would work is either
`SELECT * FROM (SELECT b FROM data1) q1 JOIN (SELECT b FROM data2) q2 ON q1.b=q2.b` so no quote chars around query aliases, or
`SELECT * FROM (SELECT b FROM data1) "q1" JOIN (SELECT b FROM data2) "q2" ON "q1".b="q2".b` so using the quote chars when referring to the aliases.

**Comment by Shawe82** [comment]
@mikeengland do you think this can be done?

**Comment by mikeengland** [comment]
I haven't had a chance to look at this yet.

The join syntax wraps the schema/table/column name in what is defined in the QUOTE_CHAR. The SnowFlakeQueryBuilder defines this as None. Changing that will break other Snowflake queries (as it would make everything case sensitive) so we'd need to do something more intelligent, such as specifying a join quote character.

If you'd like to have a go at this feel free to raise a PR and we can review it when we get some time.
