### ISSUE TITLE
Dynamic where complex clauses

### ISSUE THREAD

**Issue by cstrzelc** [kayak/pypika#450]
I would like to dynamically add OR clause depending on the input from an external list.   I don't see any documentation on how to do this or if it is possible.  

Example:
```
account_list = [ '23456', '49375', '03948' ]


Query.from_(my_table).select(my_table.product_code, my_table.account, ) \
                .where( ( my_table.product_code.like('product_1%') | \
                 my_table.product_code.like('product_2%') ) )  \
                .where( Criterion.any([my_table.account == '23456', \
                 my_table.account == '49375', my_table.account == '03948']) )
```

Is it possible to make the Criterion values from account_list no matter how many values there are in the list?

Thank you very much in advance.
-cs

**Comment by mikeengland** [comment]
Not sure if I fully understand your question, but you could just use a list comprehension inside the Criterion.any:

`
accounts = [1, 2, 3, 4, 5]
Query.from_(my_table).select(my_table.product_code, my_table.account, ) \
                .where( ( my_table.product_code.like('product_1%') | \
                 my_table.product_code.like('product_2%') ) )  \
                .where(Criterion.any([(my_table.account == acc) for acc in accounts]))

`

**Comment by mikeengland** [comment]
I'll close this for now. Please let us know if you encounter any issues.
