### ISSUE TITLE
CASE Statements with multiple conditions 

### ISSUE THREAD

**Issue by kenrick-goh** [kayak/pypika#468]
```                    
Case()
     .when(
       ((AliasedQuery("aa").user_type == 'dormant')) , True)
        .else_(False)
        .as_('dormant_previous')
                  )
```
The case statement works if there is a single condition to it. Pypika will generate out query 

```
        CASE
        WHEN "aa"."user_type"='dormant' THEN true
        ELSE false 
        END "dormant_previous"
```

However, if there are 2 conditions to it.

```, Case()
    .when(
        ((AliasedQuery("aa").user_type == 'dormant') and (AliasedQuery("bb").user_type == 'dormant')) , True
         )
         .else_(False)
         .as_('dormant_previous')
)
```

It does not capture all the conditions
```
        CASE
         WHEN "bb"."user_type"='dormant' THEN true
        ELSE false
 END "dormant_previous"
```

The documentation/ examples do not show anything related to multiple conditions in a `WHEN` statement. Attempts to use `AND` to link conditions failed as shown in the code above.

Any way to resolve this?

**Comment by Robbie-Palmer** [comment]
It would be useful to have using `&` in the tests and docs
This issue could be reopened to track adding this in
