### ISSUE TITLE
How to insert a SERIAL ID using INSERT

### ISSUE THREAD

**Issue by vishalmhjn** [kayak/pypika#473]
PostgreSQL
When the primary key is of SERIAL/ BIGSERIAL type:

sql_statement = Query.into(table).insert(DEFAULT, 1, 2,
											3, 4,
											5, 6, 7, 8
											)
should work, but
ERROR: name 'DEFAULT' is not defined

**Comment by Apexal** [comment]
Try using a PseudoColumn:

```python
from pypika import Query
from pypika.pseudocolumns import PseudoColumn

DEFAULT = PseudoColumn('DEFAULT')

sql_statement = Query.into('table_name').insert(DEFAULT, 1, 2, 3, 4, 5, 6, 7, 8)

print(sql_statement)
```

This gives you `INSERT INTO "table_name" VALUES (DEFAULT,1,2,3,4,5,6,7,8)`

**Comment by mikeengland** [comment]
Thanks @Apexal. A Pseudocolumn does seem the way to go here.

**Comment by vishalmhjn** [comment]
Thanks a lot! :)
