### ISSUE TITLE
Using .notnull() not working as expected.

### ISSUE THREAD

**Issue by amundeep** [kayak/pypika#485]
I am trying to write a part of my SQL query as the following:

```
"foo" IS NOT NULL
```

After running the following code block:

```
c1 = Field('foo').notnull()
print(f'{str(c1)}')
```
It prints:
```
NOT "foo" IS NULL
```

I am currently using PyPika v0.39.1

Edit: My intention is to run this query in AWS Athena/Presto, from my testing it appears these two statements are equivalent but from a readability/performance perspective is it possible to have the query appear as the first code block?

**Comment by mikeengland** [comment]
I believe most SQL engines will create equivalent execution plans for both statements. We don't have any plans to change this for now unless there really is a valid reason to do so. Closing for now.
