### ISSUE TITLE
Add support for DELETE queries

### ISSUE THREAD

**Issue by twheys** [kayak/pypika#5]
Add support for DELETE queries.
- DELETE FROM **\* WHERE ***

**Comment by cperrin88** [comment]
+1

**Comment by mikeengland** [comment]
Released in v0.7.0

**Comment by ikandars** [comment]
I couldn't find any docs related DELETE operation, did I missed something?

**Comment by RAbraham** [comment]
`Query.from_(table).delete().where(table.id == id)`

**Comment by itsamishra** [comment]
@ikandars nope I couldn't find the DELETE docs either, but the code snippet @RAbraham posted works
