### ISSUE TITLE
'alias' arg is not saved for FIeld

### ISSUE THREAD

**Issue by nikitanickzhukov** [kayak/pypika#501]
Hi guys!
Got an error when creating a Field instance:
```
>>> x = Field(name='yourfield', alias='myfield', table='yourtable')
>>> x.alias
>>>
```

Field has a multiple inheritance: from Criterion and JSON. Field's __init__ calls JSON's __init__ at first and passes 'alias' as the only positional argument there (which must be 'value' in JSON's __init__). Please fix it.

https://github.com/kayak/pypika/blob/8a398afb7d1e29e5191f2d7f801fc4fa59fb7d8a/pypika/terms.py#L461
https://github.com/kayak/pypika/blob/8a398afb7d1e29e5191f2d7f801fc4fa59fb7d8a/pypika/terms.py#L318

**Comment by gl3nn** [comment]
I think this is fixed by https://github.com/kayak/pypika/pull/510, can you double check and close if so?

**Comment by nikitanickzhukov** [comment]
Yes, it's fixed! Thanks!
