### ISSUE TITLE
How to build a query with blob (bytes, binary) fields?

### ISSUE THREAD

**Issue by fy0** [kayak/pypika#514]
I want to select a table by blob field, database is PostgreSQL:

```
from pypika import Query, Field

print(Query().from_('test').select(Field('foo') == b'1234').get_sql())
```

sql generated:
```sql
SELECT "foo"=b'1234' FROM "test"
```

It's cause a syntax error, how could i do this?

**Comment by twheys** [comment]
Hi Fy0,

If you'd like to use the Field class, you should do so by creating an instance of Table and referencing attributes on it like this example below. It also makes the syntax a bit easier to read. 

I suspect your problem, though, stems from using a binary string. I suppose pypika should handle serializing that but doesn't currently. Can you please share a correct example of the SQL you're trying to create?

```
from pypika import Query, Table

test = Table('test')
print(Query().from_(test).select(test.foo) == '1234').get_sql())
```

**Comment by fy0** [comment]
> Hi Fy0,
> 
> If you'd like to use the Field class, you should do so by creating an instance of Table and referencing attributes on it like this example below. It also makes the syntax a bit easier to read.
> 
> I suspect your problem, though, stems from using a binary string. I suppose pypika should handle serializing that but doesn't currently. Can you please share a correct example of the SQL you're trying to create?
> 
> ```
> from pypika import Query, Table
> 
> test = Table('test')
> print(Query().from_(test).select(test.foo) == '1234').get_sql())
> ```

Hello. I solved the problem by using placeholder.

Works on blob, array field and json fields.
