### ISSUE TITLE
query.get_sql(dialect=Dialects.POSTGRESQL) does not provide correct *empty* arrays for postgresql

### ISSUE THREAD

**Issue by MickaelAlliel** [kayak/pypika#527]
When passing it an array to insert such as `[]` it will convert to `ARRAY[]` which returns the following error in PostgreSQL:
```
ERROR:  cannot determine type of empty array at character XXX
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
```

The correct thing to do is to return `'{}'` instead of casting to a specific type that is probably unknown to Pypika. `'{}'` gives PSQL the right to cast it according to the column type.

**Comment by Apexal** [comment]
Running into the same issue. Does anyone have a workaround?

**Comment by mikeengland** [comment]
This will probably require a simple change to the Array class in pypika.terms. Would you be interested in creating a PR for this? If so, we are happy to review it.
Cheers

**Comment by prussyuval** [comment]
Seems like the problem still exists in `0.48.4` version
