### ISSUE TITLE
Select PostgreSQL stored function with Parameter

### ISSUE THREAD

**Issue by AbuSM** [kayak/pypika#540]
Hi, didn't find any solution on this:
want to select from database stored function like:
`select * from get_account_funds(<account_id>)`.
Moreover I have used joins like: 
`PostgreSQLQuery.from_(accounts).left_join(account_types)` with a few others
How could I combine them with stored function and Fields?

**Comment by gl3nn** [comment]
As discussed here (https://stackoverflow.com/questions/65663316/select-values-from-database-function-in-pypika/65675595) this can be achieved with: 
```>>> from pypika import Query
>>> from pypika.terms import Function
>>> account_id = 1
>>> Query.from_(Function('get_accounts', account_id)).select("*")
'SELECT * FROM get_accounts(1)'
```

However our typing and documentation doesn't actually support this as `Function` is not a `Selectable`. It's possible that letting `Function` inherit from `Selectable` would be enough to fix this.
