### ISSUE TITLE
Introspection in builders

### ISSUE THREAD

**Issue by espositofulvio** [kayak/pypika#542]
Hi, I don't really know if this is the right place to ask for help but I couldn't find a forum or a chat. I was wondering if there is any chance to introspect the query builder to get references to tables, fields, etc, already added to a query. I'll make an example to explain better. Imagine I want to build an sql statement dinamically, but the logic is spread in different classes/functions:

```python
stmt = PrepareUserStmt()
stmt = GetDateOfBirth(stmt)
stmt = GetAddresses(stmt)
users = db_connection.execute(stmt)
```

the three functions basically do the following:

```python
user_table = Table('users')
address_table = Table('addresses')

def PrepareUserStmt():
    return Query.from_(user_table).select(user_table.user_id)

def GetDateOfBirth(stmt):
    return stmt.select(user_table.date_of_birth)

def GetAddresses(stmt):
    return stmt.Join(addresses).using('user_id').select(address_table.street, address_table.city)
```

The above works but, for instance, GetDateOfBirth(stmt) assumes that we already added user_table. Imagine I want to generalize this system and want a way to tell if a table has already been added and get a reference to that table so that I can avoid a self join:

```python
def GetDateOfBirth(stmt):
    if user_table not in stmt:
        stmt = stmt.from_(user_table)
    return stmt.select(user_table.date_of_birth)
```

That's because sometimes I want to select only the date_of_birth, sometimes I want to add the full_name, sometimes I want only the full_name. Adding or removing a field might depend on some dynamic conditions. If I blindly did `stmt.from_(user_table)` in every composition function, I would get many self cross joins.

Is there a way to achive that with pypika?

**Comment by gl3nn** [comment]
Here or StackOverflow are a good place to ask questions. You'll probably get a faster answer on SO.

When you're constructing a query, you're working with an instance of the class `QueryBuilder`. You can simply consult the protected fields.

```
>>> user_table = Table("users")
>>> query_builder = Query.from_(user_table)
>>> user_table in query_builder._from
True
```

**Comment by espositofulvio** [comment]
Thanks, that should do the trick!
