### ISSUE TITLE
CustomFunction for Snowflake?

### ISSUE THREAD

**Issue by info-rchitect** [kayak/pypika#556]
Hi,

Is there a `Snowflake version of `CustomFunction`?  I am getting singlequotes inserted into the column name required as an argument for the custom function.

~~~python
        # I have many other select columns not shown here
        get_proberhandler_id = CustomFunction('GET_PROBERHANDLER_ID', ['mfg_components'])
        # I then add get_proberhandler_id like any other select column
~~~

This produces the following SQL:

~~~sql
SELECT master_serial_number,mfg_step_name,test_code,test_program_name,test_program_version,lot_id,hard_bin,hard_bin_description,soft_bin,soft_bin_description,mfg_components,GET_PROBERHANDLER_ID('mfg_components') FROM kdf2_unit_run WHERE unit_start_date BETWEEN '2021-02-18' AND '2021-02-25' AND product_sub_family='PRODUCTA' AND mfg_step_name='WS1'
~~~

The call to `GET_PROBERHANDLER_ID` needs to pass the argument without singlequotes to be a valid Snowflake query.  I guess having a dialect such as `SnowflakeCustomFunction` is what I am looking for.

thx

**Comment by airtonzanon** [comment]
Hello @info-rchitect 

Can you post here the SQL that you expect and the one that you're getting?

Because you say that you're getting double quotes and in your example, I see single quotes.

**Comment by info-rchitect** [comment]
@airtonzanon Sorry about that, I updated the original post to reflect single quotes are what is breaking my SQL.

**Comment by iamchairs** [comment]
Maybe try making the argument value `[Field('mfg_components')]`

If that doesn't work I've got a dozen custom functions for snowflake. But I found it easier to just write them myself.

i.e.:

```
from typing import Any

from pypika.terms import Function, Term
from pypika.utils import format_alias_sql


class StPoint(Function):
    def __init__(self, long: Term, lat: Term, **kwargs):
        self._long = long
        self._lat = lat
        self.alias = kwargs.get('alias')
        super().__init__("_", **kwargs)

    def get_sql(self, **kwargs: Any) -> str:
        sql = f"ST_POINT({self._long.get_sql(**kwargs)}, {self._lat.get_sql(**kwargs)})"
        return format_alias_sql(sql, self.alias, **kwargs)
```

**Comment by airtonzanon** [comment]
Oh, I got here and @iamchairs already had my answer haha.

I created it like this @info-rchitect 

```python
from pypika import Table, Field
from pypika.dialects import SnowflakeQuery

get_proberhandler_id = CustomFunction('GET_PROBERHANDLER_ID', ['mfg_components'])

query = SnowflakeQuery.from_(Table("test")).select(
    get_proberhandler_id(Field('mfg_components'))
)

print(query.get_sql())
# output:
# SELECT GET_PROBERHANDLER_ID(mfg_components) FROM test
```

**Comment by info-rchitect** [comment]
Thanks everyone for the help!  I am trying to use pypika to programmatically generate SQL for many of our common use cases using a data from a Jupyter UI.
