### ISSUE TITLE
Enums not quoted

### ISSUE THREAD

**Issue by cbows** [kayak/pypika#560]
# Bug report

## Description

When using a member of `class(Enum)` or `class(str, Enum)` in a query, I expect the underlying `.value` of the member to be used when constructing a query so that the result is the same as if I had passed the literal value explicitly.

## Example

```python
from pypika import Query, Table 
from enum import Enum

class Status(Enum):
    ON = 'on'
    OFF = 'off'

t = Table('tab')
q = Query.from_(t).select(t.col1).where(t.status == Status.ON)
```

## Actual behavior

```
>>> q.get_sql()
SELECT "col1" FROM "tab" WHERE "status"=on
```

## Expected behavior

```
>>> q.get_sql()
SELECT "col1" FROM "tab" WHERE "status"='on'
```

## Version info

Python 3.7.9
PyPika 0.47.7

**Comment by cbows** [comment]
Might this work #561?

**Comment by x8lucas8x** [comment]
Hey @cbows, thanks for the PR but after reviewing it once again, I believe the complexity it adds doesn't pay off. I think your use case is valid, however for custom enum like yours you have already two alternatives, which are pretty solid. The most naive one would be to call value directly in your queries:

```
q = Query.from_(t).select(t.col1).where(t.status == Status.ON.value)
```

I understand that you are however expecting something more convenient. For such you could create a custom Enum that always wrap LiteralValue around your custom values, such as:

```
class LiteralEnum(Enum):
    def __new__(cls, value):
            obj = object.__new__(cls)
            obj._value_ = LiteralValue(value)
            return obj

class Status(LiteralEnum):
    ON = 'on'
    OFF = 'off'
```

**Comment by cbows** [comment]
Hi, thanks for reviewing!

However, I think the second solution does not solve the problem that I tried to address initially.

The problem I see very generally is that `ValueWrapper` treats enum values different from normal values. So a `date` that is passed literally will be transformed to string and then quoted, but a `date` passed as a member of an enum is just unpacked and neither converted to string nor is it quoted (the same goes for booleans, strings etc.). So actually enum values are treated kind of like `LiteralValues`, which felt unintuitive to me and is not what I expected. This was fixed in https://github.com/kayak/pypika/pull/561/commits/145145434e8fd38db56cb64b36cfcea724164c3d and this was my actual concern.

The other problem (and I think this is what your second solution refers to) is something unrelated, but surfaced after running the tests with the corrected enum behavior. And I still think this is a bug, which I fixed in https://github.com/kayak/pypika/pull/561/commits/d20e3aba2812eefea14cee3f9c14ee40848054a2 

So the complexity you mention, does it refer to the changes in the first or second commit?

**Comment by cbows** [comment]
Some more thoughts:

```python
from pypika import Table, Query
from datetime import date
from enum import Enum

class E(Enum):
    STR='foo'
    DATE=date.today()

t = Table('t')
q1 = Query().from_(t).select(t.col).where(t.col == E.STR)
q2 = Query().from_(t).select(t.col).where(t.col == E.STR)

print(q1)
# prints SELECT "col" FROM "t" WHERE "col"=foo
# expected SELECT "col" FROM "t" WHERE "col"='foo'

print(q2)
# prints SELECT "col" FROM "t" WHERE "col"=2021-03-11
# expected SELECT "col" FROM "t" WHERE "col"='2021-03-11'
```

With the solution provided in https://github.com/kayak/pypika/commit/145145434e8fd38db56cb64b36cfcea724164c3d the above script would print the expected results.

The solution you provided has a couple of issues. First of all, it is arguably more complex, since not everyone is aware of the behavior of `__new__` and since you overwrite standard enum behavior in a significant way, I'd expect the application to break in other places. Also the solution has a serious flaw, because the first `value` would overwrite all other values, e.g.

```python
class LiteralEnum(Enum):
    def __new__(cls, value):
            obj = object.__new__(cls)
            obj._value_ = LiteralValue(value)
            return obj

class F(LiteralEnum):
    foo='foo'
    bar='bar'
    baz='baz'

print(F.foo) # prints <F.foo: <pypika.terms.LiteralValue object at 0xABC>>
print(F.bar) # prints <F.foo: <pypika.terms.LiteralValue object at 0xABC>>
print(F.baz) # prints <F.foo: <pypika.terms.LiteralValue object at 0xABC>>
```

To make it work you'd either create your own `Enum` with `EnumMeta` or do something else, but I wouldn't consider it less complex.

**Comment by x8lucas8x** [comment]
The complexity I mention refers to the fact that you make a DatePart also inherit from str, just to support your use case. And DatePart would be the only enum in our codebase that would rely on that. Something I doubt anyone will find standard/intuitive. Nothing against how you've made the Enum value be evaluated recursively though.

That said, you have a fair point about my initial LiteralEnum implementation not rightly formatting non basic types (e.g. dates). That said, if you use ValueWrapper instead of LiteralValue, that would behave as expected. Regarding the overwriting of all other values that is definitely undesired. An alternative such as would be more appropriate:

```
from enum import Enum, DynamicClassAttribute

class ValueWrapperEnum(Enum):
   @DynamicClassAttribute
   def value(self):
      return ValueWrapper(self._value_)
```

So my suggestion for a custom Enum, which you would maintain in your code, still holds.

**Comment by cbows** [comment]
Ok great. I think then we are on the same page. My use case is the enum quoting (handled recursively). The `DatePart` thing I don't care about as much and I can remove it from the PR, but I genuinely think this is a bug and we can discuss about it in another issue.

The important change is https://github.com/kayak/pypika/commit/145145434e8fd38db56cb64b36cfcea724164c3d which I don't find too complex and I think is the 'more correct' behavior.
