### ISSUE TITLE
Snowflake REGEXP function supported?

### ISSUE THREAD

**Issue by info-rchitect** [kayak/pypika#564]
Hi,

Is the [Snowflake REGEXP function](https://docs.snowflake.com/en/sql-reference/functions/regexp.html) supported?  I see a `regex` function in `pypika`:

~~~python
customers = Tables('customers')
q = Query.from_(customers).select(
    customers.id,
    customers.fname,
    customers.lname,
).where(
    customers.lname.regex(r'^[abc][a-zA-Z]+&')
)
~~~

Which creates:

~~~sql
SELECT id,fname,lname FROM customers WHERE lname REGEX '^[abc][a-zA-Z]+&';
~~~

Is there a way with a `dialect` to change REGEX to REGEXP?

thx

**Comment by mikeengland** [comment]
Looking at various platform docs e.g. Snowflake and MySQL, it looks like 'REGEXP' is also common. If you have time to submit a PR which creates a regexp method on the Term class (like regex), that would be a good addition. Thanks!

**Comment by info-rchitect** [comment]
@mikeengland For all the time your module saves me, making a PR is the least I could do.  thx
