### ISSUE TITLE
Inconsistent datepart handling in functions

### ISSUE THREAD

**Issue by cbows** [kayak/pypika#574]
# Bug report

There are currently 3 functions in `pypika.functions` that accept a `date_part` as an argument. That is `DateAdd`, `TimestampAdd` and `Extract`, which represent the underlying `DATE_ADD`, `TIMESTAMPADD` and `EXTRACT` SQL functions respectively. Most dialects (if not all) require the `date_part` arguments to these functions to be a keyword (unquoted, optionally all caps). However, the current implementation doesn't enforce this (at least not consistently). 

Below are some examples of the behavior

```python
from pypika import functions as fn, Table

t = Table('t')

print(fn.TimestampAdd('year', 1, '2017-10-01'))
# TIMESTAMPADD('year',1,'2017-10-01'))

print(fn.DateAdd('year', 1, '2017-10-01'))
# DATE_ADD('year',1,'2017-10-01'))

print(fn.Extract('year', t.foo)
# EXTRACT('year' FROM "foo")
```

The above examples (except the last one) are taken from the tests at https://github.com/kayak/pypika/blob/ff0e8cd8c262f8f50a9be06dcb03c26fbbe60070/pypika/tests/test_functions.py

While this might be incorrect SQL, it is the expected behavior from `pypika.terms.Function` which wraps all arguments to functions with `ValueWrapper`, so you'd expect strings to quoted, etc. However, there is one way to get function arguments formatted as SQL keywords and that is by using an enum like `pypika.enums.DatePart`

```python
from pypika.enums import DatePart

print(fn.TimestampAdd(DatePart.year, 1, '2017-10-01'))
# TIMESTAMPADD(YEAR,1,'2017-10-01'))

print(fn.DateAdd(DatePart.year, 1, '2017-10-01'))
# DATE_ADD(YEAR,1,'2017-10-01'))

print(fn.Extract(DatePart.year, t.foo)
# EXTRACT(YEAR FROM "foo")
```

This relies on a peculiar behavior of `ValueWrapper`, which treats members of enums different than their literal sibling types (i.e a string member of an enum is handled differently than a literal string). But, as described in https://github.com/kayak/pypika/issues/560, this might not be the expected or desired behavior and is also only partially tested.

The result is that I think there is an inconsitency in the definition of functions, specifically regarding those that accept SQL keywords as arguments.

## Solution

I suggest that SQL keyword function arguments are wrapped in a `LiteralValue` to avoid quoting. and to modify the function definitions in a way that they don't implicitly rely on the special enum behavior (like `Extract` does), so users who pass strings get the same result as users who pass enums.

I have materialized these suggestions in a PR which should resolve this issue.

**Comment by x8lucas8x** [comment]
The prorposal and the PR looks good. The consistency between all funcs relying on date part is definitely welcome.

**Comment by Abdeali099** [comment]
@x8lucas8x is this works on mariadb?

In mariabd : https://mariadb.com/docs/server/reference/sql-functions/date-time-functions/date_add

but this evaluate as

```
DATE_ADD(DAY,4,date_column)
```

and throws an error
