### ISSUE TITLE
Is there any way to implement the <=> sysmbol

### ISSUE THREAD

**Issue by Enternalcode** [kayak/pypika#584]
In Kudu, I need to compare the NULL in the two columns, and I need to use the <=> symbol. Is there any way to achieve this?

**Comment by x8lucas8x** [comment]
Is KUDU a SQL-like database? That said you could create a dialect for it, such as the ones in https://github.com/kayak/pypika/blob/master/pypika/dialects.py, in which you add support to that syntax. Assuming this <=> isn't supported in other SQL databases.

**Comment by Enternalcode** [comment]
I use impala to query the data in kudu. Impala supports the <=> operator (IS NOT DISTINCT FROM), but I can't implement it with pypika.
