### ISSUE TITLE
Support for "ON DUPLICATE KEY UPDATE" in mysql

### ISSUE THREAD

**Issue by wahwynn** [kayak/pypika#59]
When doing bulk adds into a mysql database it is very useful to use the "ON DUPLICATE KEY UPDATE" feature from here https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

This allows us to specify fields to be updated when the key for the row already exists.  For example:

``` sql
INSERT INTO table (a,b,c) VALUES (1,2,3)
  ON DUPLICATE KEY UPDATE c=c+1;
```

Notice that we are adding values `a, b, c` in the insert but if there is a duplicate we are only updating the `c` value.

**Comment by inkmix** [comment]
implemented in https://github.com/kayak/pypika/pull/116
