### ISSUE TITLE
How to check if a field exists within a Case statement

### ISSUE THREAD

**Issue by BadDoggie** [kayak/pypika#592]
Hi, have been using this great library for a couple of small projects and have come up with a challenge, wonder if anyone knows how to solve it? 

I have query components in a module that I import, for example a Case statement:
```
my_case = Case()  
    .when((Field('foo') == 'foo') & (Field('bar') == 'bar'), 'foo')  
    .when(Field('bar') == 'bar', 'bar')  
    .when(Field('baz') == 'baz', 'baz')  
    .else_('other')  
    .as_('alias')  
```

Then I have a series of queries defined, and can easily add that `my_case`: 
```
qry = Query().from(my_table).select(Field('foo'), Field(my_case))
```

This has worked really well for me, but now I have the problem that in some tables I'll be working with the field 'bar' doesn't exist.  Getting the list of columns from the existing table is simple enough, but I can't yet see a way to search the `.when()` statements for that field. 

I've been toying with tracing via VSCode, and see that each `.when()` contains either a BasicCriterion or a ComplexCriterion, and each of these has a "left2 and a "right" property which may contain a Field object.  Is searching through these and trying to match them up the right way to go, or am I missing something obvious / easier?

Many thanks in advance. 
Dog

**Comment by mikeengland** [comment]
Hi @BadDoggie, maybe you can iterate through my_case.nodes and check each node returned?

**Comment by BadDoggie** [comment]
Thanks @mikeengland for the idea... I tried that and certainly could see all the items. Unfortunately, I couldn't figure a way to use that to achieve what I was ultimately after - I want to remove a `.when()` clause if any of the fields don't exist in the table list. 
I've written a series of methods that check the type of each element in the clause, and based on their type check either the left, right or args recursively until I get down to a `Field()`.. (if that makes sense). Not pretty, but seems to work ok.
