### ISSUE TITLE
How to return id after insert

### ISSUE THREAD

**Issue by giangnguyen12353** [kayak/pypika#612]
i have a query like below:
INSERT INTO table (field1,field2)  VALUES('val1','val2')  RETURNING id
how can i create this query by pypika

**Comment by gleb-kov** [comment]
```PostgreSQLQuery.into(self.table_abc).insert('val1', 'val2').returning('id')```

more examples here: https://github.com/kayak/pypika/blob/master/pypika/tests/test_inserts.py#L468

**Comment by giangnguyen12353** [comment]
@gleb-kov 
thanks for your support. That works well 💯
