### ISSUE TITLE
Self Join

### ISSUE THREAD

**Issue by sevdimali** [kayak/pypika#615]
Hi, is pypika supports self join? I didn't find it in the documentation.

I see only:
**.left_join(join_table)
.right_join(join_table)
.inner_join(join_table)
.outer_join(join_table)
.cross_join(join_table)**

**Comment by anhqle** [comment]
Self join is not a special kind of join outside of the ones you listed. Self join simply means that the two tables being joined are the same table.

We can accomplish that using alias. In the following example, I'm joining `mytable` with itself.

```
In [58]: t1 = Table('mytable').as_('t1')
In [59]: t2 = Table('mytable').as_('t2')
In [61]: Query.from_(t1).join(t2).on(t1.id == t2.id).select('*')
Out[61]: SELECT * FROM "mytable" "t1" JOIN "mytable" "t2" ON "t1"."id"="t2"."id"
```

**Comment by sevdimali** [comment]
thanks.

**Comment by Ga68** [comment]
I'm trying to do the same, but not with a table, but instead an AliasedQuery. I'm using a query in a with clause, and I want to self join that CTE to itself. It seems that AliasedQuery isn't allowing/using the `as_(...)` function
