### ISSUE TITLE
Call on_duplicate_key_update multiple times dynamically

### ISSUE THREAD

**Issue by kiran-g** [kayak/pypika#621]
I am trying to generate an insert statement with  "on_duplicate_key_update" called multiple times dynamically. I want something like this:
```
q = Query.into(customers)\
    .insert(1, 'Jane', 'Doe', 'jane@example.com')\
    .on_duplicate_key_update(key1, val1)\
    .on_duplicate_key_update(key2, val2)\
    .
    .
    .on_duplicate_key_update(keyn, valn)
```
So I need to be able to do it like this:

```
q = Query.into(customers)\
    .insert(1, 'Jane', 'Doe', 'jane@example.com')
for i in zip(keys,values):
    q.on_duplicate_key_update(i[0],i[1])
```

But this is not working as the generated query does not have "ON DUPLICATE KEY UPDATE" at all. 

How can I achieve this ?

**Comment by mikeengland** [comment]
Hi @kiran-g. It looks like you are not assigning the return value of on_duplicate_key_update back to the query. Try `q = q.on_duplicate_key_update(i[0],i[1])` in your example above. Please close this if that works for you.

**Comment by kiran-g** [comment]
It worked. Thanks for the prompt reply. keep up the good work.

**Comment by kiran-g** [comment]
It worked. Thanks for the prompt reply. keep up the good work.
