### ISSUE TITLE
How to access PostgreSQL JSON fields?

### ISSUE THREAD

**Issue by phanikmr** [kayak/pypika#634]
something like the following query
select  
SUM(cast(meta -> 'risks' -> 'regions' -> 'ap-northeast-1' ->> 'num_checked' as int)) as total_checked, 
SUM(cast(meta -> 'risks' -> 'regions' -> 'ap-northeast-1' ->> 'num_flagged' as int)) as total_risks,
SUM(cast(meta -> 'risks' -> 'regions'-> 'ap-northeast-1' ->> 'num_dangers' as int)) as total_highs,
SUM(cast(meta -> 'risks' -> 'regions' -> 'ap-northeast-1' ->> 'num_warnings' as int)) as total_mediums
from findings;

**Comment by x8lucas8x** [comment]
@phanikmr we don't support PostgresSQL's JSON syntax yet, so feel free to create a pull request adding support to it in the respective dialect class.
