### ISSUE TITLE
Python None should be converted to 'NULL' instead of 'null'

### ISSUE THREAD

**Issue by mikeengland** [kayak/pypika#66]
Very low priority ticket for neatness, it would be nice if Python None converted to 'NULL' instead of 'null'

```python
str(Query.from_('testtable').select(None))
'SELECT null FROM "testtable"'
```

**Comment by spinningarrow** [comment]
Currently is there a way to build a `.where` clause that checks if a column is null? i.e. something that turns into the following SQL clause:

```sql
WHERE my_column IS NULL
```

**Comment by spinningarrow** [comment]
No worries - I found it. It's the `isnull` method. Doing `table.my_column.isnull()` works.

**Comment by twheys** [comment]
This appears to be already resolved

**Comment by mikeengland** [comment]
Strangely, it is in some places, but the update test still shows it as lower case: https://github.com/kayak/pypika/blob/f03e0cd5113182a1952bad4356858b249ff69285/pypika/tests/test_updates.py#L35

**Comment by MartinThoma** [comment]
How do you deal with missing columns for UNION ALL in Pypika?

In standard SQL, you just supply a `NULL` column ([example](https://stackoverflow.com/a/7791543/562769)).

`Field("NULL")` seems to do the trick in pypika, but `Field(None)` throws an error.
