### ISSUE TITLE
Case with subquery doesn't wrap with parentheses 

### ISSUE THREAD

**Issue by minhfix** [kayak/pypika#660]
if I try to do an case when  is a subquery, pypika doesn't wrap the subquery in parentheses within the when sub query .
      

       

         student_tbl =  Table("student")
         sub_query =(Query
                .from_(student_tbl)
                .select(student_tbl.point)
                .where(student_tbl.student_id == "001")
                )

        case_clause =  Case().when(sub_query.isnull(), 0).else_(10)
        query = (PostgreSQLQuery.into(student_tbl)
                        .columns(student_tbl.point)
                        .insert(10)
                        .on_conflict("studen_id")
                        .do_update(student_tbl.point, case_clause)
                        )

The above code generates this invalid query...

>  INSERT INTO "student" ("point") VALUES (10) ON CONFLICT ("studen_id") DO UPDATE SET "point"=CASE WHEN SELECT "point" FROM "student" WHERE "student_id"='001' IS NULL THEN 0 ELSE 10 END

When it should be...

>  INSERT INTO "student" ("point") VALUES (10) ON CONFLICT ("studen_id") DO UPDATE SET "point"= CASE WHEN ( SELECT "point" FROM "student" WHERE "student_id"='001') IS NULL THEN 0 ELSE 10 END

**Comment by ajustintrue** [comment]
@minhfix I opened the issue below for a similar problem. My workaround should work for you. It is not great but it does work 🤷 

https://github.com/kayak/pypika/issues/635

**Comment by minhfix** [comment]
> 



> @minhfix I opened the issue below for a similar problem. My workaround should work for you. It is not great but it does work 🤷
> 
> #635

**Comment by minhfix** [comment]
> @minhfix I opened the issue below for a similar problem. My workaround should work for you. It is not great but it does work 🤷
> 
> #635

 it does work for me. Thank you
