### ISSUE TITLE
UnicodeDecodeError when pip install

### ISSUE THREAD

**Issue by bluepark16** [kayak/pypika#70]
When I use pip install, UnicodeDecodeError occured.
I use Windows 7 korean version and python3.

The details of the error are as follows:
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "\<string>\", line 1, in \<module>\
      File "\AppData\Local\Temp\pip-gz8hjtca-build\setup.py", line 60, in <module>
        long_description=readme(),
      File "\AppData\Local\Temp\pip-gz8hjtca-build\setup.py", line 10, in readme
        return f.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 16934: illegal multibyte sequence

I open the setup.py file and I found that this error is caused by  'README.rst' file.
so I delete the code 'long_description=readme(),' and repack, then I install successfully.
I don't understand why this error occured, but I thought this error should be reported.
Sorry for my poor english.

**Comment by mikeengland** [comment]
Please upgrade to pypika version 0.6.6. I just pushed a fix. 

Thank you very much for reporting this!
