### ISSUE TITLE
Add order by example to README

### ISSUE THREAD

**Issue by mikeengland** [kayak/pypika#76]
As order by is such a common use case, pypika should include examples of how to add an asc and desc order by.

**Comment by simonmath** [comment]
There you go

Query.from_(authors).join(tweets).on(authors.twitter_id ==tweets.author_id_fk).orderby(tweets.created_at,order=Order.desc).select(authors.screen_name, authors.name, authors.location, authors.followers_count, authors.description, tweets.full_text, tweets.created_at, tweets.source, tweets.lang)

SELECT Authors.screen_name,Authors.name,Authors.location,Authors.followers_count,Authors.description,Tweets.full_text,Tweets.created_at,Tweets.source,Tweets.lang FROM Authors JOIN Tweets ON Authors.twitter_id=Tweets.author_id_fk ORDER BY created_at DESC

**Comment by mikeengland** [comment]
Thanks @simonmath, I actually knew how to do it, but we didn't have it in the README which may be a pain for new users. Sorry I should have been more explicit in the issue.

**Comment by simonmath** [comment]
@mikeengland no worries. I was looking myself for the solution for quite some minutes and found that thread. Just wanted to make it available for everyone :)
