### ISSUE TITLE
NOT BETWEEN possible?

### ISSUE THREAD

**Issue by info-rchitect** [kayak/pypika#772]
Hi,

I would like to create a filter such as `NOT BETEEN 0 AND 6`, is this possible?

thx

**Comment by wd60622** [comment]
Using a `~` on a `Field` negates the implemented `between`. 

For example,
```python
Query.from_("table").where(~Field("column").between(0, 6)).select("*")
```
results in 
```text
SELECT * FROM "table" WHERE NOT "column" BETWEEN 0 AND 6
```
Does that fit your use-case?

**Comment by info-rchitect** [comment]
Functionally this will work, thanks again.

**Comment by wd60622** [comment]
If this helped, feel free to close the issue

**Comment by info-rchitect** [comment]
It did indeed help, ty!
