### ISSUE TITLE
MySQL queries should wrap set operations

### ISSUE THREAD

**Issue by pandaxtc** [kayak/pypika#773]
The MySQLQuery dialect doesn't wrap set operations in parens, but UNION queries that have LIMITs and ORDERs in the subqueries fail without parens. [The documentation states](https://dev.mysql.com/doc/refman/8.0/en/parenthesized-query-expressions.html#:~:text=You%20cannot%20have%20a%20query%20block%20with%20a%20trailing%20ORDER%20BY%20or%20LIMIT%20without%20wrapping%20it%20in%20parentheses%20but%20parentheses%20may%20be%20used%20for%20enforcement%20in%20various%20ways%3A):
> You cannot have a query block with a trailing ORDER BY or LIMIT without wrapping it in parentheses...

For example, this fails:
```sql
SELECT 1 LIMIT 1 UNION SELECT 2 LIMIT 1;
```
but this does not:
```sql
(SELECT 1 LIMIT 1) UNION (SELECT 2 LIMIT 1);
```

**Comment by pandaxtc** [comment]
The example you provided uses `MSSQLQuery` instead of `MySQLQuery`. Here's an example:
```py
from pypika.dialects import MySQLQuery

query = MySQLQuery.from_("table").select("id").union(MSSQLQuery.from_("another_table").select("id"))
query.get_sql() # or str(query)
```
results in
```
'SELECT `id` FROM `table` UNION SELECT `id` FROM `another_table`'
```

**Comment by wd60622** [comment]
I misread that then. 
Here in the code, the `wrap_set_operation_queries` is set to False.
https://github.com/kayak/pypika/blob/8841520e906970d76c5ed81c7dd5d154f0d5259d/pypika/dialects.py#L90

Would you want to make a PR to change?

In the meantime, you might be able to set the `wrap_set_operation_queries` attribute of your query to True.

**Comment by pandaxtc** [comment]
The temporary solution works, thanks. I opened a PR: https://github.com/kayak/pypika/pull/782
