### ISSUE TITLE
Join on multiple columns not working

### ISSUE THREAD

**Issue by raayu83** [kayak/pypika#775]
I have a join on a subquery like this:

```
q_subquery = get_subquery().as_("q_subquery")
q = q.join(q_subquery).on(t_agg.x_id == q_subquery.x_id and t_agg.y_id == q_subquery.y_id)
```
For some reason, in the SQL generated only the second join condition is contained.

Am I doing the join the wrong way or is this a bug?

**Comment by wd60622** [comment]
> Seems you need to use & instead of and, will try this next week.

Yeah, try it with & instead of "and"

**Comment by wd60622** [comment]
Did using & resolve your issue? you will likely have to make sure that () are around the terms that you are comparing
