### ISSUE TITLE
How to order by distance?

### ISSUE THREAD

**Issue by nlassaux** [kayak/pypika#778]
I'm using distance operators in the ORDER BY, because those use geographic indexes better than their function equivalents:

```
SELECT
    id
FROM
    house h
ORDER BY
    ST_SetSRID(ST_MakePoint(%s, %s), 4326) <-> h.point
```

Unfortunately, I don't seem to find a correct way to define that custom distance. It looks like defining a custom function assumes a prefix expression notation `function_name(param1, param2)`, when I'd like a postfix version.

Has anyone covered a similar case? Thanks!

**Comment by wd60622** [comment]
What is the function here that doesn't meet the syntax `function_name(param1, param2)`?

`CustomFunction` seems to cover the two I see in your example

**Comment by nlassaux** [comment]
In that case it's the operator `A <-> B` that'd need to be computed. The functions before are all right, sorry :)

**Comment by wd60622** [comment]
For that, I think you can get away with a custom ArithmeticExpression. It'd be similar to how the primary operations are defined 

left = ... # custom functions
right = ... # column
order_by = ArithmeticExpression("<->", left, right)

# define query

**Comment by nlassaux** [comment]
That's exactly what's needed, thanks! It would be great if it was in the doc, so I opened a PR to add that: #779

**Comment by nlassaux** [comment]
Issue solved!
