### ISSUE TITLE
[bug] ImportError: cannot import name 'ClickHouseQuery' from 'pypika.dialects' (\.venv\lib\site-packages\pypika\dialects\__init__.py)

### ISSUE THREAD

**Issue by jiangying000** [kayak/pypika#781]
If i rename dialects dirname, problem solved

version: pypika 0.48.9

**Comment by jiangying000** [comment]
![image](https://github.com/kayak/pypika/assets/23182033/930aa859-507d-49c4-9889-7b4b629f6a5b)
https://pypi.org/project/PyPika/

a stale version problem

**Comment by antoninkriz** [comment]
> @antoninkriz could you help with this ?

Hi, I don't think I'm the right person to reach out to as I'm not the maintainer of this project, I made just a single contribution. Sorry.

As for the bug, I think you should provide minimal reproducible example for the developers, they'll need more information to work with.

**Comment by jiangying000** [comment]
> > @antoninkriz could you help with this ?
> 
> Hi, I don't think I'm the right person to reach out to as I'm not the maintainer of this project, I made just a single contribution. Sorry.
> 
> As for the bug, I think you should provide minimal reproducible example for the developers, they'll need more information to work with.

oh thanks,  I believe @twheys and @mikeengland are maintainers
this bug is due to excessive dialect directory at the pypi package, just download that lastest package at pypi and we can see the problem

**Comment by wd60622** [comment]
hi @jiangying000 
Can you create a reproducible example and /or explain your python setup and installation of pypika?

I am able to install the latest version and import the class in the way I'd expect:

```dockerfile
FROM python:3.11.5
RUN pip install pypika
CMD ["python", "-c", "from pypika.dialects import ClickHouseQuery; print(ClickHouseQuery); print('ClickHouseQuery was sucessfully loaded!')"]
```
```bash 
docker build -t pypika-test . && docker run pypika-test
# <class 'pypika.dialects.ClickHouseQuery'>
# ClickHouseQuery was sucessfully loaded!

**Comment by wd60622** [comment]
Did this get resolved? If so, feel free to close

**Comment by jiangying000** [comment]
Yes, sorry i forgot this

**Comment by H3d9** [comment]
> hi @jiangying000 Can you create a reproducible example and /or explain your python setup and installation of pypika?
> 
> I am able to install the latest version and import the class in the way I'd expect:
> 
> ```dockerfile
> FROM python:3.11.5
> RUN pip install pypika
> CMD ["python", "-c", "from pypika.dialects import ClickHouseQuery; print(ClickHouseQuery); print('ClickHouseQuery was sucessfully loaded!')"]
> ```
> 
> ```shell
> docker build -t pypika-test . && docker run pypika-test
> # <class 'pypika.dialects.ClickHouseQuery'>
> # ClickHouseQuery was sucessfully loaded!
> ```
> 
> Pypika doesn't have the path `pypika/dialects/__init__.py` the `ClickHouseQuery` is imported from `pypika/dialects.py`

I meet the same problem. I use pip uninstall pypika and find out that there's still a folder "dialects" in site-packages/pypika, so I delete the whole folder and reinstalled it, now it works

**Comment by datascientist89** [comment]
I have the same problem too. I'm going to use the latest version of Chromadb (0.6.3) which relies on **pypika**. I get the same error. I'm using Python 3.12.0 .

**Comment by jiangying000** [comment]
if you also install tortoise, this may  be cause by pypika-tortoise
