### ISSUE TITLE
Cannot use union result as a subquery

### ISSUE THREAD

**Issue by eddyzhow** [kayak/pypika#79]
I've tried to use result of abc and efg tables as a subquery to calculate the average value from those union tables

```
 abc, efg = Tables('abc', 'efg')
 hij = Query.from_(abc).select(abc.t).union(Query.from_(efg).select(efg.t))
 q = Query.from_(hij).select(an.Avg(hij.t))
```

but actual query I get is

```
'SELECT AVG("sq0"."t") FROM (SELECT "t" FROM "abc") "sq0"'
```

expected query should be

```
'SELECT AVG("sq0"."t") FROM ((SELECT "t" FROM "abc") UNION (SELECT "t" FROM "efg")) "sq0"'
```

Am I doing something wrong? or there is any other ways to achieve this.

Thanks

**Comment by mikeengland** [comment]
Hi @eddyzhow, thanks for reporting this. It seem like a bug in pypika. I have labelled this issue as a a bug for now.

**Comment by twheys** [comment]
Thanks for the detailed issue ticket. A PR has been raised.

**Comment by mikeengland** [comment]
This is now in version 0.9.1
