### ISSUE TITLE
Suggestion for functions

### ISSUE THREAD

**Issue by stanep** [kayak/pypika#90]
Hi , I like pypika and here is one suggestion in functions.py ,  majority of functions can use something like this

def make_func(func_name):
    cls = type(func_name,(Function,),{})
    cls.__init__ = lambda self, term, alias=None: super(cls, self).__init__(func_name, term, alias=alias)
    return cls

LTRIM = make_func('LTRIM')
RTRIM = make_func('RTRIM') 

and use it
fn.RTRIM(A.name)

**Comment by twheys** [comment]
This is a bit too abstract in my opinion and doesn't handle which arguments a function should take.  However, the verbosity of the current implementation for function wrappers could probably be reduced.  I'll take a look at improving it.

**Comment by stanep** [comment]
Sure
