### ISSUE TITLE
Select fields are surrounded by parenthesis, causing SQL statement errors

### ISSUE THREAD

**Issue by sshahar1** [kayak/pypika#92]
I am trying to automatically build the query from my configuration, it's something like this:
`query = Query.from_(table).select([Field(f) for f in typeConfig['select']])`

The issue is that the query object looks like this:
`SELECT ("field1","field2","field3") FROM "myTable"`

And converting it to string results in:
`SELECT ("field1","field2","field3") FROM "myTable"`

I did some debugging and I see the cause for that is in terms.py get_sql method:
`def get_sql(self, **kwargs):
        return '({})'.format(
            ','.join(term.get_sql(**kwargs)
                     for term in self.values)
        )`

Why is the code surrounding the terms with parenthesis? MySQL refuses this SQL query

Thanks in advance

**Comment by twheys** [comment]
This is intentional behavior, since it is possible to query tuples in most SQL databases. You need to deconstruct list that you're passing into the select function otherwise pypika will interpret it as a tuple. 

`query = Query.from_(table).select(*[Field(f) for f in typeConfig['select']])`
