### ISSUE TITLE
Invalid outer join for postgresql

### ISSUE THREAD

**Issue by Zeliboba5** [kayak/pypika#95]
Current join enum have only basic "OUTER" join, which is not supported by postgresql.
`how` parameter for joins should accept list of JoinType's, so join could be concatenated, or JoinType enum should be extended to have `LEFT OUTER' 'RIGHT OUTER' 'FULL OUTER'.

I can implement it, but would like to hear your opinion on this matter, may be I am missing something, how joins should be built with pypika

**Comment by twheys** [comment]
Thanks for reporting. This is a really small fix so I just raised a PR. To keep it simple I just added enum values for these three, since not every combination is possible, and since the list of join types is quite small and manageable.
